dasch-swiss/dsp-api

- webapi/_test_data/demo_data/images-demo-data.ttl
- webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1E2ESpec.scala
* Add missing `.` to end of `images-demo-data.ttl` so GraphDB doesn't complain about an unexpected end of file.
* Clean up `ResourcesV1E2ESpec` a bit.
> fix(demo data): Add missing . to end of images-demo-data.ttl.

- webapi/src/main/scala/org/knora/webapi/messages/v1respondermessages/searchmessages/SearchMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/SipiResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ValueUtilV1.scala
- webapi/src/main/twirl/queries/sparql/v1/searchExtended.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/searchFulltext.scala.txt
- webapi/src/test/scala/org/knora/webapi/responders/v1/SearchResponderV1Spec.scala
This branch changes search SPARQL queries and the search responder so the search queries don't get ontology information. Instead, the search responder first does the search, then asks the ontology responder for the ontology information, which it merges into the search results.
> Get ontology info from ontology responder, not from search queries

- webapi/src/main/twirl/queries/sparql/v1/searchExtended.scala.txt
This search responder test was taking 8 seconds on GraphDB SE 6.6.2:
```
should return 79 pages when we search for all pages that have a sequence number greater than 450 in the Incunabula test data
```
I moved the MINUS clause that filters out deleted resources, and it now takes 350 ms. It's still fast with Fuseki 2.3.0, too.
> perf(search): Move MINUS clause to improve extended search performance.

- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
> fix (values responder): Hide value IRIs that the user doesn't have permission to see.

- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/main/twirl/queries/sparql/v1/addValueVersion.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/changeComment.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/changeLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/createLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/createNewResource.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/createValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/deleteLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/deleteValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/getLastModificationDate.scala.txt
- webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
> fix (webapi): Update a resource's lastModificationDate when one of its values is changed

- knora-ontologies/knora-base.ttl
- webapi/src/main/scala/org/knora/webapi/util/InputValidation.scala
We have both `valueHasUri` (which is used) and `valueHasURI` (which is not used). This removes the unused one.
> Remove redundant valueHasURI property.

- webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
This is just a small improvement to error-handling.
> Return a better error message if a property has an invalid objectClassConstraint

- salsah/src/test/scala/org.knora.salsah/browser/ResourceCreationSpec.scala
- salsah/src/test/scala/org.knora.salsah/browser/SearchAndEditSpec.scala
Exclude beol data from browser test data because we do not need it.
However, beol ontology has still to be loaded because the beol named graph is not ignored when beol ontology is not loaded since this is statically defined in `application.conf`.
> tests (browser tests): remove beol data from test data

- docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst
add missing explanations for LIKE and !LIKE in the docs
> docs (extended search): add missing explanations for LIKE and !LIKE

- salsah/src/public/default.css
simple url change as the rest of my problems concerning proxying knora behind apache were not linked to knora, but to apache.
Here's the commit's comment:
```
removing relative paths to icons in css file: it doesn't survive an front apache proxy like:
<Location "/salsah/">
ProxyPass "http://localhost:3335/"
ProxyPassReverse "http://localhost:3335/"
</Location>
in order to have salsah/knora/sipi served as paths ( http://myserver.unil.ch/salsah/ ) instead of URL with their ports ( http://myserver.unil.ch:3335/ ).
```
> removing relative URL paths for http proxying

- docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst
- webapi/src/main/scala/org/knora/webapi/messages/v1/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/embedded/JenaTDBActor.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
- webapi/src/main/twirl/queries/sparql/v1/getResourceSearchResult.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/searchExtended.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/searchFulltext.scala.txt
- webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/SearchResponderV1Spec.scala
When we added support for searching for subclasses and subproperties in #283, there was a performance penalty in some cases. This pull requests optimises those cases by using inference on GraphDB.
For most of the existing search tests, the performance improvement is small, but it's significant in a few cases.
Before:
```
[info] - should return 19 books when we search for all books in the Incunabula test data (321 milliseconds)
```
After:
```
[info] - should return 19 books when we search for all books in the Incunabula test data (9 milliseconds)
```
Before:
```
[info] - should return 79 pages when we search for all pages that have a sequence number greater than 450 in the Incunabula test data (189 milliseconds)
```
After:
```
[info] - should return 79 pages when we search for all pages …
```
> Use inference to optimise searches on GraphDB

- webapi/src/main/scala/org/knora/webapi/KnoraService.scala
- webapi/src/main/scala/org/knora/webapi/http/CORSSupport.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v1/CORSSupportV1E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/http/CORSSupportV1R2RSpec.scala
- Resolves #306: DELETE method was missing in CORS configuration
- Resolves #304: `Access-Control-Allow-Origin` is missing in response header and thus the browser blocks the answer (in responses with status code other than 200).
> fix (webapi): CORS problems

- docs/update-gh-pages.sh
This adds a script that you can run manually to update the documentation on knora.org when the RST or generated API docs have changed.
The script assumes that you're on the `develop` branch and have already committed any changes you made there. It builds the docs and updates the `gh-pages` branch with the resulting HTML.
In the future we could automate this to run every time `develop` is updated.
> Add script to update docs on knora.org

- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/util/TransformData.scala
Before SALSAH correctly supported labels, labels were hard-coded as `test`, and this affected regions created by the BEOL project. This pull request adds a `regionlabels` transformation to `TransformData`, which looks for regions whose `rdfs:label` is `test`, and replaces each one's label with the `valueHasString` of its `hasComment`.
> Make TransformData fix “test” labels on regions

- salsah/src/public/js/jquery.editvalue.js
- salsah/src/public/js/jquery.propedit.js
- salsah/src/public/js/jquery.resadd.js
- salsah/src/public/js/load_infowin.js
- salsah/src/public/lang/de.json
- salsah/src/public/lang/en.json
- salsah/src/public/lang/fr.json
- salsah/src/public/lang/it.json
- salsah/src/test/scala/org.knora.salsah/browser/ResourceCreationSpec.scala
- salsah/src/test/scala/org.knora.salsah/browser/SearchAndEditSpec.scala
- webapi/scripts/fuseki-load-test-data.sh
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/v1/responder/usermessages/UserMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/messages/v1/responder/valuemessages/ValueMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/UsersResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
- webapi/src/main/twirl/queries/sparql/v1/changeLink.scala.txt
- webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
- webapi/src/test/scala/org/knora/webapi/routing/AuthenticatorSpec.scala
* Fixes #277.
* Fixes #309.
* Fixes #310.
* Closes #297 by changing `UsersResponderV1` not to return an `Option`, relying on exceptions instead, and changing `Authenticator` accordingly.
> fix (salsah): Create multiple links in a resource, and other bug fixes

- docs/rst/knora-ontologies/knora-base.rst
- knora-ontologies/knora-base.ttl
- webapi/scripts/KnoraRules.pie
- webapi/src/test/scala/org/knora/webapi/store/triplestore/GraphDBConsistencyCheckingSpec.scala
- Fix errors in `knora-base` docs (#323).
- In `knora-base.ttl`:
- Eliminate `rdfs:label rdfs:subPropertyOf :objectCannotBeMarkedAsDeleted`, and add a rule to `KnoraRules.pie` specifically for `rdfs:label` instead (#324).
- Remove unused `knora-base:hasProvider` property (#323).
- Replace `owl:AnnotationProperty` with `owl:DatatypeProperty` or `owl:ObjectProperty` (#323).
Closes #323.
Closes #324.
> Ontology and documentation fixes.

- webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV1.scala
This implements `RouteUtilV1.runHtmlRoute` to return HTML instead of JSON, and refactors RouteUtilV1 a bit to simplify it.
Closes #314.
> Return HTML instead of JSON when requested.

- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala
`knora-base:resourceProperty` has to be ignored since it is never used directly.
The query <http://localhost:3333/v1/propertylists?vocabulary=0> for property definitions for all vocabularies failed because of this error: 
> Property http://www.knora.org/ontology/knora-base#resourceProperty has no knora-base:objectClassConstraint
I added a test that now detects this problem (this test was missing and thus we did not find about about this).
> fix (ontology responder): ignore knora-base:resourceProperty 

- webapi/src/main/twirl/queries/sparql/v1/getIncomingReferencesGraphDB.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/getIncomingReferencesStandard.scala.txt
Limits the number of incoming references to 50 and thereby prevents problems when writing back too many results from the triplestore
> fix (limit incoming references): limit the number of incoming references

- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/main/twirl/queries/sparql/v1/getLinkSourceAndTargetPermissions.scala.txt
- webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
Fixes #366.
The docs say:
> Link values created automatically for resource references in standoff are automatically visible to all users, as long as they have permission to see the source and target resources.
When the values responder loads a link value, it must:
* Check the link value's permissions using `PermissionUtilV1.getUserPermissionOnLinkValueV1WithValueProps`, which takes into account the special case of standoff links.
* Check that the user has permission to view the source and target resources.
> fix (webapi): Fix permission checking on link values

- knora-ontologies/knora-admin.ttl
- removing ``knora-base:systemProperty`` from the declaration of ``knora-base:institutionWebsite``
- #378
> fix (knora-ontologies): remove obsolete property

- docs/rst/introduction/example-project.rst
Fixes #405.
* Ran `incunabula-demo-data.ttl` through `TransformData -t all`.
* Added missing `valueHasCreationDate`.
* Added text to fix empty strings.
* There were many references to sidebands, but no actual sidebands. Removed all references to sidebands.
> Fix inconsistencies in incunabula-demo-data.ttl.

- docs/rst/knora-api-server/api_v1/adding-values.rst
- docs/update-gh-pages.sh
> Make it easier to find the documentation on the date string format

- webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/twirl/ResourceToCreate.scala
- webapi/src/main/scala/org/knora/webapi/util/KnoraIdUtil.scala
This changes the function `KnoraIdUtil.makeRandomResourceIri()`:
* Include the project's shortname (which will be a unique ID) in the IRI.
* Use `rdfh.ch` as the IRI domain name. This will point to a server that redirects requests to Knora API servers depending on the project ID in the IRI.
I also removed some unused methods, and clarified and reformatted some code.
> Generate dereferenceable IRIs using the rdfh.ch hostname

- salsah/src/public/index.html
expect content-type text from sipi on login and logout (SALSAH GUI) 
Firefox (because of jQuery) attempted to parse the empty answer as XML, resulting in an error
see https://github.com/dhlab-basel/Sipi/pull/148#issuecomment-289013080
> Sipi login/logout

- webapi/src/main/scala/org/knora/webapi/responders/IriLocker.scala
- webapi/src/test/scala/org/knora/webapi/responders/IriLockerSpec.scala
If the task passed to `IriLocker.runWithIriLock` handled an error by throwing an exception instead of by returning a failed `Future`, the lock would not be released. This fixes `IriLocker` so it releases the lock in that case, and adds some tests.
Please try this `IriLocker` on your branch and let me know if it fixes the problem you saw.
> Release IRI lock if a task throws an exception instead of returning a Future

- .travis.yml
Travis-ci.org upgraded their base image used for running automated tests. This somehow broke our builds. After changing the config to use their newest image, builds are working again.
Resolves #504
> build (travis): fix build after travis update

- salsah/src/public/js/02_searchlist.js
- salsah/src/public/js/imagebase.js
fixes #492
this one was hard to find!
But in the end it is just a typo.
When the rights are set to 7, `aka Rights.RESOURCE_ACCESS_DELETE`, then the test doesn't recognize it (`Rights.VALUE_ACCESS_DELETE` = 4) and assigns the translated rights `Rights.VALUE_ACCESS_NONE`
```js
switch (data.resdata.rights) {
case Rights.RESOURCE_ACCESS_NONE: {
rights = Rights.VALUE_ACCESS_NONE;
break;
}
case Rights.RESOURCE_ACCESS_VIEW_RESTRICTED:
case Rights.RESOURCE_ACCESS_VIEW: {
rights = Rights.VALUE_ACCESS_VIEW;
break;
}
case Rights.RESOURCE_ACCESS_ANNOTATE:
case Rights.RESOURCE_ACCESS_EXTEND:
case Rights.RESOURCE_ACCESS_OVERRIDE: {
rights = Rights.VALUE_ACCESS_ANNOTATE;
break;
}
case Rights.RESOURCE_ACCESS_MODIFY:
case Rights.VALUE_ACCESS_DELETE:
case Rights.RESOURCE_ACCESS_RIGHTS: {
rights = …
```
> missing to check the Rights.RESOURCE_ACCESS_DELETE value

- docs/rst/knora-api-server/design-documentation/futures-with-akka.rst
> docs (recover future): actually use the recovered Future

- salsah/src/public/index.html
"a chain is only as strong as its weakest link" and this `http` link will stop you from being called `https` (in modern browsers)
> chain of trust

- docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst
- webapi/src/main/scala/org/knora/webapi/routing/v1/SearchRouteV1.scala
- webapi/src/main/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
- webapi/src/test/scala/org/knora/webapi/responders/v1/SearchResponderV1Spec.scala
The conditions for LT_EQ and GT_EQ were wrong. Logically, they are simply the negations of GT and LT, respectively.
closes  https://github.com/dhlab-basel/Knora/issues/575
> fix (extended search date LT_EQ GT_EQ): fix wrong conditions for date comparison

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
Fixes #627.
Fine for me because it makes it more likely that data will be returned in Arabic. :)
> When requested languages aren't available, take the first one alphabetically

- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/test/resources/test-data/searchR2RV2/IncomingLinksForBook.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptional.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOrDecimal.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
When processing the results of a prequery, some values may be optional (OPTIONAL and UNION).
We actually do not have to know whether a value was in a UNION or an OPTIONAL when processing the prequery's results because this is all handled in the prequery's WHERE clause. If a value was expected but not returned, the whole resource would not have been returned and would not be available for processing.
closes #686
> Correctly process Variables contained in UNION and OPTIONAL

- webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala
This PR comes with a refactoring that collects the incoming resources just once. Before, this was done for each resource inside the recursive function `nestResources`.
When nesting the resources, incoming resources are added only if they 
1. have not been traversed yet 
2. are not main resources themselves
1 prevents an endless recursion and 2. prevents circular references in the sense that main resources always point to dependent resources, meaning that always would be treated as incoming links. This would make no sense, since main resources are already present on the top level of the response.
closes #675
> Prevent circular references when getting incoming links

- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/twirl/StandoffTag.scala
- webapi/src/main/scala/org/knora/webapi/util/search/SparqlQuery.scala
- webapi/src/main/scala/org/knora/webapi/util/search/v2/ExplicitTypeInspectorV2.scala
- webapi/src/main/scala/org/knora/webapi/util/search/v2/SearchParserV2.scala
- webapi/src/main/scala/org/knora/webapi/util/standoff/StandoffTagUtilV1.scala
- webapi/src/main/twirl/queries/sparql/v1/addValueVersion.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/generateInsertStatementsForCreateValue.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/v1/StandoffV1R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/SearchResponderV2Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/SearchResponderV2SpecFullData.scala
- webapi/src/test/scala/org/knora/webapi/util/search/v2/SearchParserV2Spec.scala
This PR adds support for a URI value in a KnarQL query (FILTER).
It also fixes a bug in the v1 templates: URI values were stored as `xsd:string`.
This also had to fixed for standoff attributes.
closes #697
> URI values are not supported in KnarQL

- webapi/_test_data/all_data/admin-data.ttl
- webapi/_test_data/all_data/permissions-data.ttl
- webapi/_test_data/all_data/webern-data.ttl
- webapi/_test_data/ontologies/webern-onto.ttl
- webapi/_test_data/queries/webern/find_webern_person.rql
- webapi/_test_data/queries/webern/relation_via_schoenberg.rql
- webapi/scripts/graphdb-knora-test-data.expect
- webapi/src/main/resources/application.conf
- webapi/src/test/resources/test-data/ontologyR2RV2/allOntologyMetadata.json
- webapi/src/test/scala/org/knora/webapi/SharedAdminTestData.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v1/ProjectsV1E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/ProjectsResponderV1Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/UsersResponderV1Spec.scala
This small PR dupplicates #682 , now as PR from inside the project. 
As described in the original PR, it adds some basic Webern test data to the webapi (graphdb-knora-test.expect) after @subotic was so kind to explain where the necessary steps have to be taken.
It includes
creation of webern-onto.ttl,
creation of webern-data.ttl,
additions of project and test user to admin-data.ttl and
additions of permissions to permissions-data.ttl
Everything is loaded to graphdb without errors here.
Also, I added a new folder queries inside webapi to store SPARQL query files that can be used to test the data. For now, there are two very basic queries for the Webern data.
---
**Supersedes PR #682**
> feature (webapi): add basic Webern test data (internal PR)

- docs/rst/knora-api-server/deployment/webapi-getting-started.rst
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/KnoraService.scala
- webapi/src/main/scala/org/knora/webapi/Settings.scala
- webapi/src/main/scala/org/knora/webapi/routing/RejectingRoute.scala
- webapi/src/test/scala/org/knora/webapi/e2e/RejectingRouteE2ESpec.scala
- Allows defining route paths in `application.conf` which should be rejected.
- resolves #639
> feature (webapi): selective route rejection

- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
when someone submits a KnarQL query for a textual match, use the logical operator AND to make sure all the terms occur in the results. By default, Lucene uses a logical OR.
> add support for logical AND for a textual match

- .travis.yml
- webapi/WebapiBuild.sbt
- add custom merge strategy used by the `assembly` task (creating fat jars)
- add running of `sbt stage` to travis (uses the `assembly` task)
- resolves #749
> build (webapi): add custom merge strategy

- .travis.yml
When a commit is tagged, like for our releases, then the publish stage, during which the docker images are built, should also run for these tags, so that the docker images are also tagged with the release tag.
> build (travis): add execution of publish stage when on tag

- docs/rst/00-release-notes/v1.3.0.rst
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/messages/v1/responder/ontologymessages/OntologyMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2Simple.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjects.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/util/jsonld/JsonLDUtil.scala
- webapi/src/main/twirl/queries/sparql/v2/changeClassLabelsOrComments.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/changePropertyLabelsOrComments.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/createClass.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForCreateProperty.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForPredicates.scala.txt
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjects.json
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjectsHasColor.json
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/v2/responder/ontologymessages/InputOntologiesV2Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
The case class `PredicateInfoV2` stores the objects of predicates of ontology entities. Currently, `PredicateInfoV2` stores all its objects as strings. When ontology information is converted from one schema to another, objects that are actually IRIs have to be converted. Since `PredicateInfoV2` doesn't know the types of its objects, something else has to keep track of that. So there are hard-coded sets of predicates that are known to have IRIs as objects, but this is cumbersome. It also means that to convert an IRI, `PredicateInfoV2` needs to convert a string to a `SmartIri` and back again.
This PR takes advantage of the type information that comes with `SparqlExtendedConstructResponse` to enable `PredicateInfoV2` to store store IRIs as `SmartIri` objects instead of strings.
As a result, …
> Use types from the triplestore in predicate objects in ontologies

- salsah1/Dockerfile
- add bash package to final alpine linux based image which does not come with bash but we need it and so on and on goes the description of this pr :-)
> build (salsah1): add bash to final image

- docs/rst/00-release-notes/v1.4.0.rst
- salsah1/src/public/js/imagebase.js
- salsah1/src/public/js/jquery.location.js
This is PR #768, adapted for the current `develop`.
The Knora-Sipi integration tests pass.
@loicjaouen Can you check that this does what you want? If so, I think we can merge it.
fixes: #726
> Fix image orientation in SALSAH 1 (moved from #768)

- webapi/WebapiBuild.sbt
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
- webapi/src/main/scala/org/knora/webapi/routing/RejectingRoute.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
- webapi/src/test/resources/logback-test.xml
- webapi/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
- system admin can now change passwords of other users
- removed code for checking SHA-1 hashed passwords. remnants of times gone by.
- resolves #795
> feature (webapi): allow changing of user’s password by system admin

- docs/src/paradox/03-webapi/api-v2/reading-and-searching-resources.md
- webapi/_test_data/all_data/anything-data.ttl
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/searchmessages/SearchMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/SearchRouteV2.scala
- webapi/src/main/twirl/queries/sparql/v2/searchFulltext.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/searchFulltextGraphDB.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/searchFulltextStandard.scala.txt
- webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptional.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/ThingWithRichtextWithTermTextInParagraph.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/SearchResponderV2Spec.scala
This PR replaces https://github.com/dhlab-basel/Knora/pull/826 (the branch `wip/standoff_search` still has to be deleted once this PR is merged).
This PR provides the possibility to restrict a fulltext search to a standoff class.
> feature (search v2): limit fulltext search to standoff class

- docs/src/jekyll/Gemfile.lock
```
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated kramdown 1.17.0, but your Gemfile requires kramdown 1.16.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```
> Try to fix docs build breakage on Travis

- .travis.yml
- docs/DocsBuild.sbt
- docs/src/paradox/05-internals/development/build-process.md
- docs/src/paradox/06-salsah/index.md
- salsah1/src/test/scala/org.knora.salsah/browser/SearchAndEditSpec.scala
Fixes failing tests in automated tests for Salsah1. Adds more instructions how run the automated browser tests for Salsah 1.
replaces #831 
closes #847
> Fix Browser Tests for Salsah1

- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/Settings.scala
- webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
- webapi/src/test/scala/org/knora/webapi/routing/AuthenticatorSpec.scala
- webapi/src/test/scala/org/knora/webapi/routing/JWTHelperSpec.scala
- add unit to `jwt-longevity`
- resolves #957
> feature (webapi): add unit to jwt-longevity setting

- .travis.yml
- webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
- webapi/src/main/twirl/queries/sparql/admin/getProjectAdminMembers.scala.txt
- webapi/src/main/twirl/queries/sparql/admin/getProjectMembers.scala.txt
- webapi/src/main/twirl/queries/sparql/admin/getUsers.scala.txt
- webapi/src/main/twirl/queries/sparql/admin/updateUser.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
- filter out the `System` and `Anonymous` user from any API requests thus not returning it
- not allow any kind of changes to these users
- resolves #772
> feature (webapi): not return or allow changing of built-in users

- docs/src/paradox/00-release-notes/v1.8.0.md
- docs/src/paradox/02-knora-ontologies/knora-base.md
- webapi/_test_data/ontologies/anything-onto.ttl
- webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-inherits-prop-and-subprop-onto.ttl
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/GraphDBConsistencyCheckingSpec.scala
This prevents the problem described in #978.
Fixes #978.
> Don't allow class with cardinalities on P and on a subproperty of P

- docs/src/paradox/00-release-notes/v1.8.0.md
- docs/src/paradox/03-apis/api-v2/ontology-information.md
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
Fixes #988.
@lrosenth could you try this branch?
> Automatically add link value prop cardinality with link prop cardinality

- .travis.yml
- docker-compose.yml
- docs/src/paradox/00-release-notes/v2.x.x.md
- docs/src/paradox/04-deployment/configuration.md
- webapi/src/main/resources/application.conf
> feature (webapi): expose additional configuration settings as environment variables

- docs/src/paradox/00-release-notes/v3.x.x.md
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ValueUtilV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/util/jsonld/JsonLDUtil.scala
- webapi/src/main/scala/org/knora/webapi/util/standoff/StandoffTagUtilV2.scala
- webapi/src/test/resources/test-data/resourcesR2RV2/CreateResourceWithEscape.jsonld
- webapi/src/test/resources/test-data/valuesE2EV2/CreateValueWithEscape.jsonld
- webapi/src/test/resources/test-data/valuesE2EV2/UpdateValueWithEscape.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
This fixes two bugs:
- After a resource was created in API v2, and the values were read back from the triplestore to check that they were saved correctly, the saved values were compared with escaped expected values (e.g. a linefeed would be `\n`). This fixes the comparison so the expected values are unescaped (like the ones read from the triplestore).
- When a `StandoffUriTag` was read from the triplestore, it was given a `StandoffTagIriAttributeV2` instead of a `StandoffTagUriAttributeV2`.
Fixes #1069.
> Fix unescaping in update check and reading standoff URL

- docs/src/paradox/00-release-notes/next.md
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
When adding cardinalities to a class definition, we don't allow the client to submit link value properties. Instead, they're supposed to submit link properties, and we generate the corresponding link value properties automatically. The bug fixed here is that if the class already contains a link value property, the error-checking mistakenly thinks that it's from the input being processed.
Fixes #1137.
> Fix error-checking when updating cardinalities in ontology API

- docs/src/paradox/00-release-notes/next.md
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
If you try to use a link value property in a Gravsearch query in the simple schema, you get a confusing error message. This fix returns a better error message, saying that the property is not found.
Fixes #1138.
> Reject link value properties in Gravsearch queries in the simple schema

- docs/src/paradox/00-release-notes/next.md
- docs/src/paradox/03-apis/api-v2/editing-resources.md
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjectsTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
- webapi/src/main/twirl/queries/sparql/v2/changeResourceMetadata.scala.txt
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.ttl
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
This adds an API v2 route for updating the following resource metadata:
Also:
Resolves #1088.
Resolves #1015.
> Update resource metadata in API v2

- docs/src/paradox/00-release-notes/next.md
- docs/src/paradox/03-apis/api-v2/query-language.md
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2SimpleTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjectsTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/GravsearchQueryChecker.scala
- webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala
- webapi/src/test/resources/test-data/ontologyR2RV2/boxOntologyWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/boxOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/boxOntologyWithValueObjects.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologyWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologyWithValueObjects.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaPageAndBookWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaPageAndBookWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaPageAndBookWithValueObjects.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/standoffOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/searchR2RV2/ProjectsWithOptionalPersonOrBiblio.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/bookWithIncomingPagesOnlyLink.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/bookWithIncomingPagesWithAllRequestedProps.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/booksWithPage100.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/incomingPagesForBook.jsonld
Corresponding PR in `Knora-ui`: https://github.com/dhlab-basel/Knora-ui/pull/148
Fixes #1135.
> Fix property names for incoming links

- docs/src/paradox/00-release-notes/next.md
- docs/src/paradox/03-apis/api-v1/adding-resources.md
- docs/src/paradox/03-apis/api-v2/editing-resources.md
- project/Dependencies.scala
- webapi/src/main/resources/knoraXmlImport.xsd
- webapi/src/main/scala/org/knora/webapi/messages/v1/responder/resourcemessages/ResourceMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/messages/v1/responder/valuemessages/ValueMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
- webapi/src/main/scala/org/knora/webapi/twirl/SparqlTemplateResourceToCreate.scala
- webapi/src/main/twirl/queries/sparql/v1/createLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/createNewResources.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/createValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/generateInsertStatementsForCreateLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/generateInsertStatementsForCreateValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/generateInsertStatementsForStandoffLinks.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/createLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/createNewResources.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/createValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForCreateLink.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForCreateValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForStandoffLinks.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
> Allow setting resource creation date in bulk import

- docs/src/paradox/00-release-notes/next.md
- webapi/_test_data/ontologies/anything-onto.ttl
- webapi/src/main/resources/knoraXmlImport.xsd
This bug is complicated to explain but easy to fix.
In the XML schemas that are used to check an API v1 bulk import, for each resource class that's used as the `objectClassConstraint` of a property, there needs to be an XML element type for elements representing links to resources of that class. For example, if you have a property `hasPerson` with an `objectClassConstraint` of `Person`, you get an automatically generated XML element type like this:
```xml
<xs:complexType name="Person_linkValueType">
<xs:sequence>
<xs:element name="Person" type="knoraXmlImport:linkValueType"/>
</xs:sequence>
</xs:complexType>
```
These element types are generated for project-specific resource classes (in the Twirl template `xmlImport.scala.xml`), but element types for resource classes in `knora-base` are …
> Allow hasRepresentation in an ontology used in a bulk import

- docs/src/paradox/00-release-notes/next.md
- webapi/_test_data/ontologies/example-ibox.ttl
- webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
Fixes #1175:
If a class definition in ontology A uses a property definition from shared ontology B, the property's XML label is not converted correctly to an internal property IRI when bulk import data is uploaded.
> Fix processing of shared property in bulk import

- docs/src/paradox/00-release-notes/next.md
- webapi/src/main/scala/org/knora/webapi/util/standoff/StandoffTagUtilV2.scala
- webapi/src/test/scala/org/knora/webapi/util/standoff/StandoffTagUtilV2Spec.scala
When verifying whether a value was saved correctly, we compare the saved value with the one that was supposed to be saved. Before we can compare standoff, we call `StandoffTagUtilV2.makeComparableStandoffCollection`, which normalises insignificant differences to make the standoff comparable. The bug in #1221 is that one of these insignificant differences is not taken into account: if the order of standoff tag attributes is different, the standoff incorrectly appears to be different.
Fixes #1221.
> Ignore order of attributes when comparing standoff

- webapi/src/main/scala/org/knora/webapi/Settings.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
- webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
In external ontology IRIs, always use `http` instead of `https`, and don't include a port number, unless Knora's external API hostname is `localhost` or `0.0.0.0`.
@subotic I don't know how to test this.
Fixes #1261.
> fix(api-v2): Make external ontology IRIs dereferenceable over https

- docs/src/paradox/03-apis/api-v2/resource-permalinks.md
This updates a paragraph of the docs on ARK URLs, which I forgot to update in #1214.
> docs(api-v2): Update outdated ARK documentation

- webapi/src/main/scala/org/knora/webapi/messages/store/sipimessages/SipiMessages.scala
This PR improves Knora's error checking if Sipi's `knora.json` route returns an empty filename or MIME type, as in #1268.
Resolves #1268.
> fix(sipi): Improve error checking of Sipi's knora.json response

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
> fix(api-v2): Remove INFORMATION SEPARATOR TWO from text in the simple schema

- docs/src/paradox/00-release-notes/next.md
- docs/src/paradox/03-apis/api-v2/query-language.md
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2SimpleTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/SparqlQuery.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/types/GravsearchTypeInspectionUtil.scala
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.ttl
- webapi/src/test/resources/test-data/searchR2RV2/ThingWithListNodeLabel.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/ThingWithListValue.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/thingNotReferringToSpecificListNode.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/thingReferringToSpecificListNode.jsonld
- webapi/src/test/resources/test-data/searchR2RV2/thingReferringToSpecificListNodeWithSubnodes.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/InstanceChecker.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
This PR supports list nodes in Gravsearch:
In a future PR I will do some refactoring so the list node label (simple schema) is returned in a deterministic way (user's preferred language), using the list responder (see #1317 ).
closes #1312
> Support list nodes in Gravsearch

- webapi/_test_data/all_data/anything-data.ttl
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/v1/responder/valuemessages/ValueMessagesV1.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2ComplexTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala
- webapi/src/main/twirl/queries/sparql/admin/getFileValueGraphDB.scala.txt
- webapi/src/main/twirl/queries/sparql/admin/getFileValueStandard.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/getFileValuesForResource.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/getValueGraphDB.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/getValueStandard.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForValueContent.scala.txt
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.ttl
- webapi/src/test/scala/org/knora/webapi/e2e/admin/SipiADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/GraphDBConsistencyCheckingSpec.scala
> fix(sipi): Don't try to read a file value in a deleted resource

- KnoraBuild.sbt
> fix(build): Fix port in use error

- upgrade/plugins/pr1367/knora-ontologies/knora-admin.ttl
This updates the `rdf:comment` strings in `knora-admin`, which I forgot to do in #1367.
> fix(upgrade): Update knora-admin comments

- webapi/_test_data/all_data/anything-data.ttl
- webapi/src/main/twirl/queries/sparql/v1/addValueVersion.scala.txt
- webapi/src/main/twirl/queries/sparql/v1/generateInsertStatementsForCreateValue.scala.txt
- webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForValueContent.scala.txt
- webapi/src/test/resources/test-data/resourcesR2RV2/Testding.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
> fix: Ensure xsd:decimal is used for interval values

- docs/src/paradox/03-apis/api-v2/permalinks.md
- docs/src/paradox/05-internals/design/api-v2/ark.md
Resolves #1407.
Thanks @mrivoal for asking about this.
> docs(ark): Document ARK URLs for projects

- webapi/src/main/scala/org/knora/webapi/responders/v2/search/SparqlTransformer.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/mainquery/GravsearchMainQueryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
This fixes a bug in the generation of a unique variable name for a `LinkValue` in the SPARQL prequery generated from a Gravsearch query.
Fixes #1416.
@gfoo could you please test this?
> fix(gravsearch): Fix generation of variable name for link value

- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/util/jsonld/JsonLDUtil.scala
- webapi/src/test/resources/test-data/resourcesR2RV2/ThingWithUnicodeEscape.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
If a resource is created with an `rdfs:label` containing escaped characters, these need to be unescaped when comparing the label in the request with the label in the saved resource.
Fixes #1452.
> fix(api-v2): Fix checking of label of newly created resource

- KnoraBuild.sbt
- docs/src/paradox/03-apis/api-util/health.md
- docs/src/paradox/03-apis/api-util/index.md
- docs/src/paradox/03-apis/api-util/version.md
- webapi/src/it/scala/org/knora/webapi/e2e/VersionRouteITSpec.scala
- webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
- webapi/src/main/scala/org/knora/webapi/routing/VersionRoute.scala
Add version endpoint at `GET /version` to retrieve the deployed versions of the Knora-stack components.
resolves #1444
> feat(webapi): Add version route

- docs/src/paradox/05-internals/design/client-api/index.md
- webapi/_test_data/typescript-client-mock-src/json2typescript.ts
- webapi/_test_data/typescript-client-mock-src/models/admin/custom-converters/administrative-permissions-per-project-converter.ts
- webapi/_test_data/typescript-client-mock-src/models/admin/custom-converters/groups-per-project-converter.ts
- webapi/_test_data/typescript-client-mock-src/models/admin/permission.ts
- webapi/_test_data/typescript-client-mock-src/models/api-response-data.ts
- webapi/_test_data/typescript-client-mock-src/rxjs/ajax.ts
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraAdminToApiV2ComplexTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/AdminClientApi.scala
- webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
- webapi/src/main/scala/org/knora/webapi/util/clientapi/ClientApi.scala
- webapi/src/main/scala/org/knora/webapi/util/clientapi/ClientCollectionTypeParser.scala
- webapi/src/main/scala/org/knora/webapi/util/clientapi/GeneratorFrontEnd.scala
- webapi/src/main/scala/org/knora/webapi/util/clientapi/TypeScriptBackEnd.scala
- webapi/src/main/twirl/clientapi/typescript/generateTypeScriptClass.scala.txt
- webapi/src/main/twirl/clientapi/typescript/generateTypeScriptEndpoint.scala.txt
- webapi/src/test/scala/org/knora/webapi/util/StringFormatterSpec.scala
- webapi/src/test/scala/org/knora/webapi/util/clientapi/ClientCollectionTypeParserSpec.scala
This PR adds support for the collection types `Map` and `Array`, by allowing a collection type signature to be defined in an IRI. Collection types defined in this way can then be represented as collection types in the target language.
Resolves #1504.
Needs https://github.com/dasch-swiss/knora-api-js-lib/pull/99.
> feat(clientapi): Support collection classes

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
> fix(api-v2): Don't assume a deleted value has a delete comment

- upgrade/graphdb-se/auto-upgrade.sh
- upgrade/graphdb-se/upload-repository.sh
> fix(upgrade): Don't strip newlines when uploading TriG file to GraphDB

- README.md
Following the doc here:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#example-using-the-branch-parameter
> Fix workflow status badge to show develop branch

- webapi/src/main/scala/org/knora/webapi/routing/admin/AdminClientApi.scala
> fix(clientapi): Fix property names.

- salsah1/src/public/js/imagebase.js
`presistent` instead of `persistent`
closes #1547
> typo in label

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
This PR fixes ontology deletion so that the ontology is removed not only from the triplestore, but also from the ontology cache.
Fixes #974.
> fix(api-v2): Fix ontology deletion

- webapi/src/main/scala/org/knora/webapi/routing/admin/GroupsRouteADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
This PR changes the signature of the client API function `updateUserSystemAdminMembership` as requested in #1579.
Resolves #1579.
> feat(clientapi): Change signature of function to update user's system admin membership

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2ComplexTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2SimpleTransformationRules.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiDate.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiDate.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiDate.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.ttl
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.rdf
- webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologyWithValueObjects.ttl
This PR:
- Fixes the definitions of custom datatypes in the `knora-api` ontology in the simple schema.
- Adds `rdfs:label a owl:DatatypeProperty` so it can be used in cardinalities.
@tobiasschweizer Do you think this will affect `knora-api-js-lib`?
Fixes #1593.
> fix(api-v2): Fix custom datatypes in knora-api simple ontology

- sipi/Makefile
> fix: sipi makefile

- webapi/src/main/scala/org/knora/webapi/responders/IriLocker.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/util/CacheUtil.scala
- webapi/src/test/scala/org/knora/webapi/responders/IriLockerSpec.scala
Fixes https://dasch.myjetbrains.com/youtrack/issue/DSP-181.
> fix(OntologyResponderV2): Add a global ontology cache lock

- webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
This PR removes some obsolete functions that I forgot to remove a long time ago.
User story:
https://dasch.myjetbrains.com/youtrack/issue/DSP-130
> chore: Remove obsolete functions from StringFormatter

- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
In `SearchRouteV2R2RSpec`, `private val writeTestDataFiles = true` should be `false` so the test is actually run.
> test: Fix typo

- docs/src/paradox/03-apis/api-v2/query-language.md
- webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/GravsearchQueryChecker.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/types/GravsearchTypeInspectionRunner.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/types/InferringGravsearchTypeInspector.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/search/gravsearch/types/IntermediateTypeInspectionResult.scala
- webapi/src/test/resources/test-data/searchR2RV2/ZeitglöckleinViaLabel.jsonld
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/search/gravsearch/GravsearchParserSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryTransformerSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/search/gravsearch/types/GravsearchTypeInspectorSpec.scala
User story: https://dasch.myjetbrains.com/youtrack/issue/DSP-271
> feat(api-v2): Allow querying for rdfs:label in Gravsearch

- .github/workflows/main.yml
Resolves [DSP-424](https://dasch.myjetbrains.com/youtrack/issue/DSP-424)
> Publish on release only

- .github/workflows/main.yml
The gren (github release notes) was in the wrong place in github actions workflow. It should work in the next release.
> Fix gren issue in github actions workflow

- webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/ClientApiRouteE2ESpec.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-229#focus=streamItem-4-577.0-0
This PR includes a test data file `delete-ontology-response.json` in the test data returned by the `clientapitest` route.
> test(clientapi): Return delete ontology response

- docs/src/paradox/03-apis/api-admin/groups.md
- docs/src/paradox/03-apis/api-admin/lists.md
- docs/src/paradox/03-apis/api-admin/projects.md
- docs/src/paradox/03-apis/api-admin/users.md
- webapi/src/main/scala/org/knora/webapi/SharedTestDataADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/groupsmessages/GroupsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/Responder.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/GroupsRouteADM.scala
- webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/GroupsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/GroupsResponderADMSpec.scala
This PR makes creation of groups with custom IRIs possible:
**Todo:**
Resolves [DSP-244](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-35?issue=DSP-244)
> Create a group with a custom IRI

- webapi/src/main/scala/org/knora/webapi/SharedTestDataADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
This PR resolves [DSP-510](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-42?issue=DSP-510)
> dummy response for create resource + getClass with allLanguages=true 

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/changePropertyLabelsOrComments.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-561
> fix(api-v2): Fix generated SPARQL for updating property comment

- docs/05-internals/design/api-v2/gravsearch.md
- webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryTransformer.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-567
> refactor(gravsearch): Clarify optimisations

- docs/03-apis/api-v2/query-language.md
- docs/05-internals/design/api-v2/gravsearch.md
- webapi/scripts/fuseki-dump-repository.sh
- webapi/scripts/fuseki-upload-repository.sh
- webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlQuery.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToCountPrequeryTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/AnnotationReadingGravsearchTypeInspector.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/GravsearchTypeInspectionUtil.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/InferringGravsearchTypeInspector.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/types/GravsearchTypeInspectorSpec.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-534
> feat(api-v2): Make inference optional in Gravsearch

- docs/02-knora-ontologies/knora-base.md
- webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/getFileValueGraphDB.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/getFileValueStandard.scala.txt
https://dasch.myjetbrains.com/youtrack/issue/DSP-582
This PR rewrites the `getFileValue` SPARQL templates to use a `CONSTRUCT` query that seems to be more efficient with Jena than the current `SELECT` query is.
> fix(sipi): Improve performance of file value query

- docs/04-publishing-deployment/publishing.md
Fix make targets docker-build and docker-publish
Fix Dockerhub Organization name and link.
> docs: fix publishing

- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-594
> fix(gravsearch): When link property compared in filter, don't compare link value property, too

- docs/03-apis/api-v2/editing-resources.md
- docs/03-apis/api-v2/editing-values.md
- webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-543
> feat(api-v2): Accept custom new value IRI when updating value

- docs/03-apis/api-v2/ontology-information.md
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
- webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/createOntology.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
resolves [DSP-548](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-50?issue=DSP-548)
closes #1690
> Add comments to ontology metadata 

- .github/workflows/main.yml
We still use gren which generates release notes on each release automatically. This PR resolves the issue we had with `release candidates`.
> chore: Update ci workflow

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-626
> fix(OntologyResponderV2): Fix ontology cache update when ontology metadata changed

- docs/03-apis/api-admin/groups.md
- docs/03-apis/api-admin/permissions.md
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/PermissionsRouteADM.scala
- webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/PermissionsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADMSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/PermissionsResponderADMSpec.scala
resolves [DSP-557](https://dasch.myjetbrains.com/youtrack/issue/DSP-557)
resolves [DSP-580](https://dasch.myjetbrains.com/youtrack/issue/DSP-580) Documentation of Permissions end point added
**BreakingChanges**:
- route to get administrative permission for a project group has an extra segment `ap`. The entire route is now `admin/permissions/ap/$projectIri/$groupIr`
- the test data for response of getting administrative permission for a project group is now in: `get-administrative-permission-for-project-group-response.json`
> Get Project Permissions

- webapi/src/test/scala/org/knora/webapi/R2RSpec.scala
After the test finishes, the data can be found in:
`bazel-testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec/test_outputs/outputs.zip`
> test: fix generation of test data (DSP-665)

- docs/03-apis/api-v2/query-language.md
- docs/05-internals/design/api-v2/gravsearch.md
- test_data/all_data/beol-data.ttl
- test_data/searchR2RV2/LetterNotToSelf.jsonld
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/InferringGravsearchTypeInspector.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/IntermediateTypeInspectionResult.scala
- webapi/src/test/resources/logback-test.xml
- webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/types/GravsearchTypeInspectorSpec.scala
https://dasch.myjetbrains.com/youtrack/issue/DSP-656
Closes #1441.
> feat(gravsearch): Allow comparing variables representing resource IRIs

- third_party/versions.bzl
- webapi/src/main/scala/org/knora/webapi/store/iiif/SipiConnector.scala
resolves [DSP-733](https://dasch.myjetbrains.com/youtrack/issue/DSP-733)
> chore: bump sipi to rc.7 (DSP-733)

- docs/requirements.txt
- mkdocs.yml
I figured out that the Github actions script for deploying the docs uses the latest version of mkdocs-material that contains a breaking change. So I had to update the configuration in documentation.
> docs: Update required mkdocs package

- docs/05-internals/development/generating-client-test-data.md
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
resolves [DSP-841](https://dasch.myjetbrains.com/youtrack/issue/DSP-841)
> fix(api-v2): Fix post-update check for resource with standoff link (DSP-841)

- .github/pull_request_template.md
- .github/workflows/main.yml
resolves DSP-877
In this PR:
- Add [Upload files to a GitHub release](https://github.com/marketplace/actions/upload-files-to-a-github-release) action
- Result should look like <https://github.com/dasch-swiss/knora-api/releases> --> s. assets
- Runs only on release
- Additional: Update Github PR template
> DSP-877 Upload api-client-test-data to GitHub release

- docs/03-apis/api-admin/lists.md
- webapi/scripts/expected-client-test-data.txt
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
> DSP-804: create a child node with a custom IRI

- docker-compose.yml
> DSP-1022 SIPI_EXTERNAL_HOSTNAME doesn't contain the external hostname

- webapi/src/main/scala/org/knora/webapi/messages/BUILD.bazel
> DSP-1029: Add the missing dependency

- docs/03-apis/api-v2/introduction.md
- test_data/metadataE2EV2/metadata-flat.jsonld
- test_data/metadataE2EV2/metadata.ttl
- webapi/src/main/scala/org/knora/webapi/OntologySchema.scala
- webapi/src/main/scala/org/knora/webapi/http/handler/KnoraExceptionHandler.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtil.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraRequestV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/MetadataRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/rdf/JsonLDUtilSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/rdf/KnoraResponseV2Spec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtilSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/rdf/jenaimpl/BUILD.bazel
- webapi/src/test/scala/org/knora/webapi/messages/util/rdf/rdf4jimpl/BUILD.bazel
> feat(api-v2): Control JSON-LD nesting via an HTTP header (DSP-1084)

- docs/03-apis/api-admin/lists.md
- docs/03-apis/api-admin/lists_new-list-admin-routes_v1.md
- test_data/all_data/anything-data.ttl
- webapi/scripts/expected-client-test-data.txt
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/lists/NewListsRouteADMFeature.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/lists/updateListItemsRouteADM.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/changeParentNode.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/DeleteListItemsRouteADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/UpdateListItemsRouteADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
resolves DSP-1033
new route for this: PUT `admin/lists/<nodeIri>/position`. Requires `parentIri` and the new `position` in the request body.
> DSP-1033 Reposition List Nodes

- docs/05-internals/design/principles/rdf-api.md
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/messages/util/rdf/jenaimpl/JenaModel.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfModelSpec.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR1307Spec.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR1372Spec.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR1615Spec.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginSpec.scala
> chore(rdf-api): Use the Jena RDF API implementation by default (DSP-1153)

- .github/pull_request_template.md
- README.md
Since [latest release (v12.0.0)](https://github.com/dasch-swiss/dsp-api/releases/tag/v12.0.0) we implemented a lot of new features and did some refactoring. Some changes were kind of breaking changes which are not recognised by just new implemented [release-please-action](https://github.com/marketplace/actions/release-please-action) because of wrong commit message schema. This PR is for all the breaking changes since v12.0.0 to enforce a new major release v13.0.0 (generated with gren, based on labels (old way))
- [#1724](https://github.com/dasch-swiss/knora-api/pull/1724) | test: Collect client test data from E2E tests (DSP-724)
- [#1727](https://github.com/dasch-swiss/knora-api/pull/1727) | DSP-740 Update List Name
- [#1722](https://github.com/dasch-swiss/knora-api/pull/1722) | …
> feat!: New features and refactoring

- .github/pull_request_template.md
- .github/workflows/main.yml
- CHANGELOG.md
In the last release (v13.0.0) we had some issues with release-please and the deployment of the documentation. This PR should fix it.
> chore(gh-ci): fix issue in the release process

- .github/workflows/main.yml
> chore(ghi-ci): google chat release notification (DSP-1155)

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
> fix(api-v2): Don't allow an invalid cardinality on a boolean property (DSP-1236)

- webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/MetadataResponderV2Spec.scala
> fix(HttpTriplestoreConnector): Always decode triplestore responses as UTF-8 (DSP-1238)

- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesUtilADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/UpdateListItemsRouteADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
resolves DSP-1251
Allow `comments:[]` in payload of routes 
- `PUT: /admin/lists/<listItemIri>/comments`
- `PUT: /admin/lists/<listItemIri>`
> fix (ListsEndPoint) Allow empty comments (DSP-1251 )

- webapi/src/main/scala/org/knora/webapi/messages/util/standoff/StandoffTagUtilV2.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/findLinkValueByIri.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/findLinkValueByObject.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/v1/BUILD.bazel
- webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
This PR improves the performance of the API v1 SPARQL queries that find link values when using Fuseki.
resolves DSP-1243
> fix(api-v1): Optimise link value queries for Fuseki (DSP-1243)

- webapi/src/main/scala/org/knora/webapi/exceptions/Exceptions.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/BUILD.bazel
- webapi/src/test/scala/org/knora/webapi/store/triplestore/HttpTriplestoreConnectorSpec.scala
> feat(store): Return a clearer exception when a triplestore read timeout occurs (DSP-1242)

- .github/workflows/main.yml
We have to be sure, that everything runs well before publishing new version of DSP-API. The last release was not successful because of failing `make client-test-data` command. This PR brings back this step to github actions. The release publish process depends on a successful generation of client-test-data.
> chore(gh-ci): Bring back the client-test-data command to github actions

- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
> fix(Lists): Repositioning the node when new position equals length of new parent's children (DSP-1322)

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
resolves DSP-1323
resolves DSP-1324
> feat(api-v2): Allow resubmitting existing class/property lablels/comments (DSP-1323, DSP-1324)

- Makefile
- docs/05-internals/development/building-and-running.md
> chore: make targets for adding metadata (DSP-1289)

- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/findResourceWithValue.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/findValueInVersions.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getContextStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getIncomingReferencesStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getRegionsStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getResourcePropertiesAndValuesStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getResourceSearchResultStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getResourcesByProjectAndType.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getValueStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/getVersionHistoryStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/isPartOfStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchFulltextStandard.scala.txt
> fix(api-v1): Optimise some SPARQL patterns for Fuseki (DSP-1325)

- test_data/all_data/anything-data.ttl
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/DeleteListItemsRouteADME2ESpec.scala
> fix(Lists): fix bug in deleting the single child of a node (DSP-1355)

- test_data/all_data/anything-data.ttl
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/DeleteListItemsRouteADME2ESpec.scala
> fix(Lists): Shift the second of two children after deletion of the first (DSP-1353)

- docs/03-apis/api-admin/permissions.md
- docs/03-apis/api-admin/projects.md
- test_data/all_data/permissions-data.ttl
- webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/PermissionsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/PermissionsResponderADMSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
- webapi/src/test/scala/org/knora/webapi/sharedtestdata/SharedOntologyTestDataADM.scala
- webapi/src/test/scala/org/knora/webapi/sharedtestdata/SharedPermissionsTestData.scala
> feat(projects): add default set of permissions when creating new project (DSP-1347)

- webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/MetadataRouteV2E2ESpec.scala
> feat(store): Return 404 if the triplestore returns 404 (DSP-1391)

- webapi/src/main/scala/org/knora/webapi/messages/util/MessageUtil.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/replaceClassCardinalities.scala.txt
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
> fix(api-v2): Fix replacement of cardinalities (DSP-1402)

- webapi/src/main/scala/org/knora/webapi/responders/v1/StandoffResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResponderWithStandoffV2.scala
- webapi/src/main/scala/org/knora/webapi/store/iiif/SipiConnector.scala
- webapi/src/test/scala/org/knora/webapi/it/v1/KnoraSipiIntegrationV1ITSpec.scala
If a default XSL transformation isn't found for a standoff mapping, returns an error message like:
```
org.knora.webapi.exceptions.SipiException: Default XSL transformation
<http://rdfh.ch/0801/smVjS18pSpyBm_TeTiXuoA> not found for mapping
<http://rdfh.ch/projects/yTerZGyxjZVqFMNNKXCDPF/mappings/leooLetterMapping>:
Unable to get file http://sipi:1024/0801/3QlCAYIGInS-G2RGy0nWAkk/file from Sipi as requested by
org.knora.webapi.responders.v2.StandoffResponderV2: Not Found"
```
resolves DSP-1404
> feat(api-v2): Improve error message when an XSLT transformation file is not found (DSP-1404)

- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchQueryOptimisationFactory.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/AnnotationReadingGravsearchTypeInspector.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/GravsearchTypeInspectionUtil.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryTransformerSpec.scala
> fix(gravsearch): Keep rdf:type knora-api:Resource when needed (DSP-1407)

- webapi/src/main/scala/org/knora/webapi/routing/v1/ValuesRouteV1.scala
> fix(values v1 route): fix geoname case (DSP-1487)

- docs/03-apis/api-v1/reading-and-searching-resources.md
- docs/08-lucene/index.md
> docs(v1): improve search docs (DSP-1553)

- Makefile
- WORKSPACE
- third_party/dependencies.bzl
> chore(deps): bump versions (DSP-1569)

- webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/lists/NewListsRouteADMFeature.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/lists/OldListsRouteADMFeature.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
> fix(lists): Escape special characters in comment, label, and name of a list node (DSP-1529)

- .github/workflows/main.yml
resolves DSP-1605
I updated the gh actions workflow, but accidentally I pushed the changes into the main branch which shouldn't be possible. You'll see the changes in commit bb852c9d and 88da8bc3. In the second commit I commented the if statement in the step "deploy documentation only on release" to see, if it runs (s. [here](https://github.com/dasch-swiss/dsp-api/runs/2527170125?check_suite_focus=true)). In this PR I uncommented the line again.
> chore(documentation): bug fix in documentation deployment (DSP-1605)

- Makefile
> feat(conf): Rule to dump prod data and load locally (DSP-1485)

- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/TopologicalSortUtil.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryTransformerSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/TopologicalSortUtilSpec.scala
> feat(gravsearch): use layer info for topological order permutations (DSP-1389)

- docs/03-apis/api-v2/reading-and-searching-resources.md
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/resourceAndValueEventsUtil.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/v2/responder/resourcesmessages/ResourcesMessagesV2Spec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
> feat(resourceHistoryEvents): route for resource history events (DSP-1749)

- docs/03-apis/api-admin/projects.md
- docs/03-apis/api-v2/knora-iris.md
- webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
- webapi/src/test/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADMSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
> fix(api-v2, api-admin): ontology name and project name should be URL safe (DSP-1749)

- webapi/scripts/expected-client-test-data.txt
- webapi/src/test/scala/org/knora/webapi/e2e/admin/PermissionsADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
> fix(add-test-file): add response file for test case (DSP-1841)

- docs/03-apis/api-admin/users.md
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
> docs: add username to changeable attributes (DSP-1895)

- docs/03-apis/api-v2/ontology-information.md
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/CORSSupportE2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
> refactor(ontology)!: use patch instead of delete for deleting cardinalities (DSP-1700)

- webapi/scripts/expected-client-test-data.txt
- webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/Cardinalities.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
> fix(candeletecardinalities): return correct response on route negative case (DEV-36)

- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/ProjectPayloadsADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UserPayloadsADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/ValueObjectsADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
In addition to DEV-64 implementing escaping characters, which has been already done, we have added the value objects handling for projects route.
> refactor(projects): refactor projects route with value objects (DEV-64)

- .github/workflows/main.yml
- CODEOWNERS
- WORKSPACE
- sipi/scripts/file_info.lua
- third_party/versions.bzl
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
> build: bump sipi version (DEV-188)

- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/NewListsRoutesADMFeatureE2ESpec.scala
> fix(list): add support for special characters in list update (DEV-200)

- webapi/src/main/scala/org/knora/webapi/routing/KnoraRoute.scala
> refactor: improve validation handling (DEV-228)

- WORKSPACE
- third_party/versions.bzl
> build: bump java and sipi version (only security updates) (DEV-263)

- Makefile
- README.md
- docker-compose.yml
> build: fix issues with fuseki (DEV-277)

- README.md
> fix: Update readme (DEV-254)

- knora-ontologies/knora-base.ttl
- webapi/src/main/scala/org/knora/webapi/package.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
> fix(version-upgrade): add upgrade plugin for ArchiveRepresentation and DeletedResource (DEV-467)

- third_party/dependencies.bzl
- third_party/versions.bzl
> chore(deps): upgrade Jena to v4.3.2 (DEV-473)

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- webapi/src/test/scala/org/knora/webapi/models/OntologyModels.scala
> feat(ontologies): make comments optional for property and class creation (DEV-342)

- docs/03-apis/api-admin/permissions.md
> docs: fix markdown issues in documentation (DEV-504)

- webapi/src/main/resources/application.conf
> fix(timeout): Increase timeouts (DEV-536)

- webapi/src/main/scala/org/knora/webapi/routing/VersionRoute.scala
- webapi/src/test/scala/org/knora/webapi/it/VersionRouteITSpec.scala
> fix(version): fix displayed versions

- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
Issue Number: DEV-478
I have updated all scala deps which are marked as compatible with Scala 3, except two (`rdf4j-client`, `rdf4j-shacl`) which generate error. I moved them and described in separate issue: DEV-765.
> build: inventory and upgrade of dependencies (DEV-478)

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/changeClassLabelsOrComments.scala.txt
Resolves DEV-508
Issue Number: DEV-508
> Fix: Problem with updating cache after deleting comments (DEV-508)

- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/test/scala/org/knora/webapi/responders/v2/ListsResponderV2Spec.scala
- webapi/src/test/scala/org/knora/webapi/sharedtestdata/SharedListsTestDataADM.scala
> fix(admin): return list labels and comments sorted by language

- .gitignore
- knora-ontologies/knora-base.ttl
- test_data/upgrade/pr2094.trig
- webapi/src/main/scala/org/knora/webapi/package.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR2079.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR2094.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR2094Spec.scala
> fix!: transform valueHasUri values from node to string type (DEV-1047)

- build.sbt
- docker-compose.yml
- sipi/config/sipi.docker-test-config.lua
- sipi/scripts/basexx.lua
- sipi/scripts/get_knora_session.lua
- sipi/scripts/sipi.init.lua
- webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/FilesRouteADM.scala
- webapi/src/test/resources/logback-test.xml
- webapi/src/test/scala/org/knora/webapi/e2e/v2/AuthenticationV2E2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/it/v2/KnoraSipiAuthenticationITSpec.scala
- webapi/src/test/scala/org/knora/webapi/testcontainers/SipiTestContainer.scala
> fix(authentication): make cookie name unique between environments

- .github/workflows/dependency-graph.yml
- .github/workflows/scala-steward.yml
> build: add dependency checking

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
Resolves DEV-1116
Issue Number: DEV-1116
> fix(ontology): link value property is still not editable after updating the property metadata (DEV-1116)

- .github/workflows/main.yml
- sipi/scripts/get_knora_session.lua
Resolves DEV-1135
Issue Number: DEV-1135
> fix(sipi): cookie parsing can cause an error which leads to 404 for images (DEV-1135)

- sipi/scripts/sipi.init.lua
> fix(sipi): SIPI returns 404 instead of images if cookie is invalid (DEV-1135)

- docs/01-introduction/file-formats.md
- sipi/scripts/file_info.lua
- webapi/src/main/resources/application.conf
> docs: update file formats (DEV-1185)

- .scala-steward.conf
- .scalafmt.conf
- project/Dependencies.scala
- webapi/src/main/scala/org/knora/webapi/instrumentation/InstrumentationSupport.scala
> chore: update dependencies

- webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
> fix(v2 test): fix test data collection

- docs/01-introduction/file-formats.md
- docs/03-apis/api-v2/editing-values.md
- sipi/scripts/file_info.lua
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/messages/util/ValueUtilV1.scala
- webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV1.scala
> fix(sipi): remove support for audio/mp4 file format (DEV-1300)

- project/Dependencies.scala
> chore: bump dependencies

- .github/workflows/build-and-test-empty.yml
- .github/workflows/build-and-test.yml
> chore: Skip tests with Success (DEV-1112)

- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
> fix: API returns invalid file URLs, due to including the port

- webapi/src/main/scala/org/knora/webapi/core/ActorSystem.scala
- webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
- webapi/src/main/scala/org/knora/webapi/core/HttpServer.scala
- webapi/src/main/scala/org/knora/webapi/core/State.scala
- webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
> refactor: app actor cleanup

- webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
> fix: Timeout for multiple Gravsearch queries (DEV-1379)

- dsp-shared/src/main/scala/dsp/valueobjects/V2.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/CreateListItemsRouteADME2ESpec.scala
> fix: DSP-API project IRI validation fails for BEOL project IRI

- Makefile
- docs/03-apis/api-admin/index.md
- docs/03-apis/api-admin/users.md
- docs/05-internals/design/principles/design-overview.md
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/HealthRoute.scala
- webapi/src/main/scala/org/knora/webapi/store/iiif/IIIFServiceManager.scala
- webapi/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
> fix: User can be project admin without being project member (DEV-1383)

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/FilesRouteADM.scala
> fix: Don't log hashes (DEV-1442)

- docs/03-apis/api-v2/introduction.md
> docs: Remove warning which considers v2 as not production ready

- docker-compose.yml
- sipi/scripts/export-moving-image-frames.sh
Issue Number: DEV-1513
This PR contains fixes which prevent the key frame extraction and matrix file creation of the two files:
https://github.com/dasch-swiss/4124-xmlperformance-testdata/blob/main/bitstreams/0.1.mp4
https://github.com/dasch-swiss/4124-xmlperformance-testdata/blob/main/bitstreams/100.mp4
Both files suffer from two different bugs:
1. Fixes processing of very short moving images (0.1.mp4)
The file is too short for any frame to be extracted with the previous implementation which assumed at least five keyframes to be extracted. Change the script to start extracting keyframes at time unit 0, i.e. the beginning of the file and use the first extract frame as the start of the …
> fix: key frame extraction (DEV-1513)

- sipi/scripts/log_util.lua
- sipi/scripts/sipi.init.lua
Previously SIPI Lua logs did not have a any timestamps attached. This PR introduces it to some - can be used as a template for future works on the lua script. On the long run we should have this done for all log calls in the lua scripts
> chore(SIPI): add timestamp to some SIPI Lua logs

- docs/03-endpoints/api-admin/permissions.md
- docs/05-internals/design/api-admin/administration.md
Adds a tabular overview of all routes of the endpoint. Could serve as a first step towards an improved structure of documentation that eventually should be applied to all documented endpoints.
> docs: improve permissions documentation

- build.sbt
- project/plugins.sbt
- webapi/src/main/scala/org/knora/webapi/Main.scala
- webapi/src/main/scala/org/knora/webapi/auth/JWTService.scala
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/core/HttpServerWithZIOHttp.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/resourceAndValueEventsUtil.scala
- webapi/src/main/scala/org/knora/webapi/store/cache/config/CacheServiceConfig.scala
- webapi/src/main/scala/org/knora/webapi/store/iiif/api/IIIFService.scala
- webapi/src/main/scala/org/knora/webapi/store/iiif/domain/SipiKnoraJsonResponse.scala
- webapi/src/main/scala/org/knora/webapi/store/iiif/errors/Errors.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/defaults/DefaultRdfData.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/errors/Errors.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdater.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/UpgradePlugin.scala
- webapi/src/main/scala/org/knora/webapi/util/Debug.scala
Add https://github.com/sbt/sbt-header plugin and missing Apache 2.0 headers to webapi project.
Headers can be added using `sbt webapi/headerCreate` and checked using ` sbt webapi/headerCheck`
I have not found out how to do a proper setup with the multiproject setup we have. But this is already an improvement.
Add sbt plugin for adding missing apache-2.0 copyright headers
> Add sbt-header plugin to webapi project and add missing headers

- Makefile
It's bringing back the functionality of `stack-up` target, basically running only backend stack.
> chore: add stack-without-app target

- docs/03-endpoints/api-admin/introduction.md
- docs/03-endpoints/api-admin/overview.md
- docs/03-endpoints/api-admin/stores.md
Add missing documentation to admin endpoints docs.
> docs: update admin documentation

- webapi/src/it/scala/org/knora/webapi/CoreSpec.scala
- webapi/src/it/scala/org/knora/webapi/E2ESpec.scala
- webapi/src/it/scala/org/knora/webapi/ITKnoraLiveSpec.scala
- webapi/src/it/scala/org/knora/webapi/R2RSpec.scala
- webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
- webapi/src/it/scala/org/knora/webapi/e2e/v1/SipiV1R2RSpec.scala
- webapi/src/it/scala/org/knora/webapi/e2e/v2/ValuesV2R2RSpec.scala
- webapi/src/it/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala
- webapi/src/it/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
- webapi/src/it/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
- webapi/src/it/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/core/HttpServer.scala
Reduce the number of integration-test layers to two and extract common layers to a single `val`.
Issue Number: DEV-628
> chore: Simplify layer setup for integration-tests and reduce to two layers

- webapi/src/it/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/RestProjectsService.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
- webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala
Issue Number: DEV-1587
[DEV-1587]: https://dasch.atlassian.net/browse/DEV-1587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: expose GET /admin/projects as ZIO HTTP route

- webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyHelpers.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/model/Cardinality.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/CardinalityService.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/CardinalityServiceLiveSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/model/CardinalitySpec.scala
A cardinality includes another cardinality if and only if the other cardinality is included in its entire range of possible values.
The previous method `isStricterThan` assumes/suggests a commutative property in the sense that when comparing different cardinalities `a` and `b` then if the comparison `a isStricterThan b == false` then `b isStricterThan a == true` must also hold. However, this is not the always the case as for example it is with `ZeroOrOne` and `AtLeastOne`. Both cardinalities are "stricter" than the other as their range of values only has a very small intersection and none contains the other in full. In the future with the introduction of other cardinalities e.g. ExactlyTwo an intersection might not even occur.
Issue Number: DEV-1563
Please check if your PR fulfills the …
> refactor: Replace Cardinality isStricterThan with isIncludedIn

- webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala
In [PR 2413](https://github.com/dasch-swiss/dsp-api/pull/2413), the test file in test/resources was deleted by the route after the test run without re-creating it. As a consequence, the next test run failed. The problem is fixed now by the test creating its own test file (which can then safely be deleted by the route afterwards).
> fix: Test file issue

- webapi/src/it/scala/org/knora/webapi/ITTestDataFactory.scala
- webapi/src/it/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
In IntelliJ IDEA the compile does not separate the source sets of test and it so it would fail with a duplicate class being present.
In IntelliJ IDEA the compile does not separate the source sets of test and it so it would fail with a duplicate class being present.
> chore: Rename TestDataFactory -> ITTestDataFactory

- webapi/src/it/scala/org/knora/webapi/responders/admin/GroupsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala
Issue Number: DEV-1599
The same was applied to `GET: /admin/groups/<groupIri>/members` route.
> fix!: return empty list instead of an error on GET /admin/groups route (DEV-1599)

- webapi/src/it/scala/org/knora/webapi/E2ESpec.scala
- webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
- webapi/src/it/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/StoreRequest.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/responders/EntityAndClassIriService.scala
- webapi/src/main/scala/org/knora/webapi/responders/IriLocker.scala
- webapi/src/main/scala/org/knora/webapi/responders/IriService.scala
- webapi/src/main/scala/org/knora/webapi/responders/Responder.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/UnsafeZioRun.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
- webapi/src/main/scala/org/knora/webapi/util/ActorUtil.scala
- webapi/src/main/scala/org/knora/webapi/util/ZioHelper.scala
- webapi/src/test/scala/org/knora/webapi/util/ZioHelperSpec.scala
Issue Number: DEV-1728
Migrates the `ProjectsResponderADM` into ZIO land.
* Introduces `ProjectsResponderADM` trait which exposes the methods from the receive/handle to the outside world for possible direct use
* Adds a live implementation and layer for above trait
* Adds a ZIO implementation for the `IriLocker`
* Adds a `ZioHelper` object which implements functions for `ZIO`s akin to Scala's `Future#sequence` functions
* Adds overloaded `Triplestore#sparqlHttpExtendedConstruct` methods which accepts a `String`
* Fixes handling of errors in `ActorUtil#zio2Message`, all causes are sent back to the actor as failure
PR is based on https://github.com/dasch-swiss/dsp-api/pull/2453 that is why I have set this as the merge target for now so that you do not have to review the other PR twice. …
> refactor: Ziofy ProjectsResponderADM DEV-1728

- .github/workflows/build-and-test-empty.yml
With this change it should be possible again, to make the integration test workflow required.
> chore: add missing github-actions workflow

- Makefile
- docs/05-internals/design/api-admin/administration.md
- docs/requirements.txt
- mkdocs.yml
> docs: minor improvements to permissions documentation

- webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
Fix ResourceUtilV2.doSipiPostUpdate so that it does not evaluate the provided `updateTask` multiple times but folds over the result instead.
This problem does not occur if the provided task is coming from a future as then it is containing simply a value and evaluating the value twice does not change the outcome. But will be a problem once the updateTask is coming from a real ZIO which contains instructions being evaluated multiple times then.
> fix: doSipiPostUpdate to evaluate provided task only once (NO-TICKET)

- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/countPropertyUsedWithClass.scala.txt
- webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/CardinalityServiceLiveSpec.scala
Issue Number: DEV-1878
Adds a test for the case that the object of a property was deleted.
Given a deleted property the count query should count instances with deleted properties with a count of zero instead of removing the instance from the result set entirely.
> fix: deleted properties in cardinalities should be included in the count query (DEV-1878)

- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/CardinalityService.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/OntologyRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyRepoLive.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/CardinalityServiceLiveSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/OntologyCacheDataBuilder.scala
When traversing the super-classes for a set of given subclasses for each super-class branch we have to stop the search at the branch from which the search begun so that we do not include the class for which the cardinality should be set.
Issue Number: (DEV-1927)
> fix: Allow setting a cardinality in a three tier class hierarchy (DEV-1927)

- sipi/scripts/export-moving-image-frames.sh
In DSP-TOOLS e2e Tests, there is a "Bad substitution" warning in this part of the code. This fixes it.
> fix: Fix bad substitution in export-moving-image-frames.sh

- webapi/src/it/scala/org/knora/webapi/messages/util/search/SparqlTransformerSpec.scala
- webapi/src/it/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformerSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlQuery.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/InferenceOptimizationService.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/ConstructTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/OntologyInferencer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/SelectTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/SparqlTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/WhereTransformer.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/GravsearchTypeInspectionUtil.scala
Currently, `LuceneQueryPattern` is the only type in the Gravsearch AST which doesn't correspond to valid SPARQL, and it always gets transformed away into the same statement.  
This PR removes the unnecessary type from the AST system.
> refactor: improve lucene handling in gravsearch (DEV-2148)

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
Supply the empty argument list `()` explicitly to invoke method toObjsWithLang
In Scala 3, an unapplied method like this will be eta-expanded into a function.
> chore: Resolve compiler warning toObjsWithLang (NO-TICKET)

- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/groupsmessages/GroupsMessagesADM.scala
> chore: Remove unused GroupShortADM (NO-TICKET)

- webapi/src/it/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/it/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformerSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
> fix: gravsearch and count queries include deleted resources for some queries with negation patterns (DEV-2189)

- CHANGELOG.md
> chore: fix invalid links (DEV-2251)

- sipi/scripts/authentication.lua
- sipi/scripts/strings.lua
- webapi/src/it/scala/org/knora/sipi/SipiIT.scala
fix: Make Sipi split multiple cookies by ; as defined in the Cookie spec
The `Cookie` header value may contain a list of name value pairs.
A list of name-value pairs in the form of `<cookie-name>=<cookie-value>`.
Pairs in the list are separated by a semicolon and a space (`; `).
[ https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie ]
> fix: Multiple cookies are separated by `; ` not by `,` (DEV-2271)

- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
Minor logging improvements and extracting duplicated code to private method.
> refactor(TriplestoreServiceLive): minor improvements

- docker-compose.yml
- docs/04-publishing-deployment/configuration.md
- webapi/src/it/scala/org/knora/webapi/ITKnoraLiveSpec.scala
- webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
- webapi/src/it/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportServiceIT.scala
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/Main.scala
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/KnoraProject.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ZipUtility.scala
- webapi/src/test/scala/org/knora/webapi/config/AppConfigSpec.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClientMock.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportServiceStub.scala
> feat: Dsp-ingest integration for import/export of projects DEV-2297

- webapi/src/main/scala/dsp/valueobjects/Project.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectRepo.scala
- webapi/src/test/scala/dsp/valueobjects/ProjectSpec.scala
Issue Number: DEV-2399
Align import and export endpoint to use `Shortcode` as identifier in both routes.
Remove unused factory method `Shortcode.make(Option[String])`.
> fix: Align path variable for export and import routes to use Shortcode

- docker-compose.yml
> chore: Add docker compose configuration for api accessing ingest

- docs/05-internals/design/api-v2/ontology-management.md
- webapi/src/it/scala/org/knora/webapi/CoreSpec.scala
- webapi/src/it/scala/org/knora/webapi/core/TestStartupUtils.scala
- webapi/src/it/scala/org/knora/webapi/e2e/admin/StoreADME2ESpec.scala
- webapi/src/it/scala/org/knora/webapi/responders/v2/LoadOntologiesSpec.scala
- webapi/src/it/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/core/AppRouter.scala
- webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/StoresResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCache.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCacheFake.scala
* Use `OntologyCache` directly where `AppRouter` was used before
* Remove unused `LoadOntologiesRequestV2` message
> refactor: Remove ontology responsibility from AppRouter

- build.sbt
We need to add two new labels to our DSP-API images to make source code linking work on DataDog.
https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=errortracking#tag-your-telemetry
I've also added `org.opencontainers.image.version` so that we overwrite the inherited version of the ubuntu base image (= "20.04") with the version/tag of DSP-API image.
Issue Number: INFRA-328
> chore: add some OCI docker image labels to DSP-API for DataDog source code linking (INFRA-328)

- build.sbt
- project/Dependencies.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClientLiveSpec.scala
For some reason the zio-http `Client` fails to download a 23 GB+ project from ingest with an `OutOfMemoryException` even though it should be streaming the response directly into the file.
`java.lang.OutOfMemoryError: Cannot reserve 1052352512 bytes of direct buffer memory (allocated: 1078845448, limit: 2126512128)`
Exchange the http client with an `sttp` implementation which uses the standard Java `HttpClient` under the hood.
Set the maximum time to wait for the download to 30 minutes (the 23 GB took around 22 minutes to create).
> refactor: Use sttp client for dsp-ingest download

- build.sbt
- integration/src/test/scala/org/knora/webapi/e2e/CORSSupportE2ESpec.scala
- integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
- integration/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- integration/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/main/scala/org/knora/webapi/core/HttpServerZ.scala
- webapi/src/main/scala/org/knora/webapi/http/directives/DSPApiDirectives.scala
- webapi/src/main/scala/org/knora/webapi/instrumentation/health/HealthRouteZ.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
> chore: improve compiler warnings (DEV-1611)

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/repo/service/KnoraProjectRepoInMemory.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectRepoInMemory.scala
Load Ontologies from db with single query and parallelise converting `KnoraProject` to `ProjectADM`
NO-TICKET
I found that loading the start page with the project overview takes very long.
This is partly due to the fact that the app is loading the projects list with  `/project` which is a slow endpoint, which is also called twice during initial loading.
This change speeding up the conversion of a `KnoraProject` to a richer `ProjectADM` by parallelising the lookup of the ontology a project is attached to. Since the cache and an actual database lookup are pretty similar I have also removed the dependency on the `OntologyCache`.
> refactor: Speedup /projects endpoint

- integration/src/test/scala/org/knora/webapi/store/triplestore/TriplestoreServiceLiveSpec.scala
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemorySpec.scala
Adds metrics timer for query execution time, metrics key is`fuseki_request_duration`, tags are the `isGravSearch=[true|false]` and `type=[Ask|Construct|Select|Update]`.
Queries which take longer than a configurable threshold (`KNORA_WEBAPI_TRIPLESTORE_FUSEKI_QUERY_LOGGING_THRESHOLD`) are logged as info. Default threshold is one second.
Removes unused methods from `TriplestoreService`: `insertDataGraphRequest`, `dropAllTriplestoreContent` and `sparqlHttpGraphData`.
Renames `sparqlHttpGraphFile` to `downloadGraph`.
Simplifies return type of `checkTriplestore()` to `Task[TriplestoreStatus]`.
> feat: Add metrics to TriplestoreService SparqlQuery execution DEV-2627

- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/InferringGravsearchTypeInspector.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/StandoffResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/CardinalityHandler.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyHelpers.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCache.scala
Removed compiler warning:
pattern var ... in value $anonfun is never used: use a wildcard `_` or suppress this warning with `...@_`
> refactor: Remove type annotations which produce compiler warnings

- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
Create 7 buckets for upper bounds 10ms, 100ms, 1s, 10s, 1.6m, 16.6m, inf
Issue Number: DEV-2627
> chore: Update 'fuseki_request_duration' histogram bucket boundaries

- integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
- integration/src/test/scala/org/knora/webapi/routing/AuthenticatorSpec.scala
- integration/src/test/scala/org/knora/webapi/routing/JwtServiceSpec.scala
- integration/src/test/scala/org/knora/webapi/util/ZioScalaTestUtil.scala
- webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
- webapi/src/main/scala/org/knora/webapi/routing/JwtService.scala
> feat: SystemAdmins receive a token which is valid on the dps-ingest api

- webapi/src/main/scala/org/knora/webapi/routing/AroundDirectives.scala
In Datadog we have a lot of warn messages:
[405] HEAD http://api.dasch.swiss/admin/projects took: 1ms
[404] NOT_FOUND http://api.dasch.swiss/admin/projects took: 1ms
However, there is nothing we can do about a client using a method which is not supported and NotFound responses are also expected to happen. Hence, reduce the logging to debug in these cases.
> chore: Do not log warn message for 405 and 404 status code responses

- .scala-steward.conf
https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md
> chore: Configure Scala Steward to produce PR with compatible title

- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
[Update wiremock to 3.2.0](https://github.com/dasch-swiss/dsp-api/pull/2868/commits/8a91ce8a789c76dde2a48994b72ea07f619d2f94) https://github.com/dasch-swiss/dsp-api/pull/2866 
[Update sbt to 1.9.6](https://github.com/dasch-swiss/dsp-api/pull/2868/commits/d5c82ab50c81198ba88baccdc5409e0f9bdb8856) https://github.com/dasch-swiss/dsp-api/pull/2864 
[Update zio-metrics-connectors, ... to 2.2.0](https://github.com/dasch-swiss/dsp-api/pull/2868/commits/19326cbdbcb65013dac45abf84d3566c7ac39d17) https://github.com/dasch-swiss/dsp-api/pull/2862 
[Update zio, zio-macros, zio-test, ... to 2.0.18](https://github.com/dasch-swiss/dsp-api/pull/2868/commits/d790ecbc60221f1ddb67bf770c55aedd128a2eaa) https://github.com/dasch-swiss/dsp-api/pull/2861 
[Update sbt-twirl, twirl-api to …
> chore: Update dependencies DEV-2742

- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- project/Dependencies.scala
- webapi/src/main/scala/dsp/errors/Errors.scala
- webapi/src/main/scala/dsp/valueobjects/Iri.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
- webapi/src/main/scala/org/knora/webapi/routing/BaseEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/routing/HandlerMapperF.scala
- webapi/src/main/scala/org/knora/webapi/routing/PathVariables.scala
- webapi/src/main/scala/org/knora/webapi/routing/TapirToPekkoInterpreter.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsEndpointsHandlerF.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
Migrate all public ProjectEndpoints to Tapir
> refactor: Introduce tapir on Pekko

- docs/05-internals/design/api-admin/administration.md
> docs: Remove invalid ProjectAdminOntologyAllPermission (DEV-2814)

- webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala
> fix: Return permissions and do not throw exception for FileValues with more than one version (DEV-2855)

- webapi/src/main/scala/org/knora/webapi/core/InstrumentationServer.scala
- webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala
* move the `forkDaemon` into the for comprehension when starting the instrumentation server
* remove unused layers from `ProjectsServiceLiveSpec`
> refactor: Remove/Fix some compiler warnings

- .github/workflows/build-and-test.yml
- Makefile
- integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
The dedicated zio-http routes do not exist anymore.
> chore: Remove GitHub action which tests zio-http routes 

- docker-compose.yml
- integration/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
> feat(Gravsearch): Enable ORDER BY external link (DEV-2704)

- .scala-steward.conf
> chore: Group dependency updates

- integration/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToCountPrequeryTransformerSpec.scala
- integration/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformerSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/GravsearchQueryChecker.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchQueryOptimisation.scala
I have tested this change with a couple of queries, e.g. from DEV-2675, DEV-2699.
It seems like these queries benefit drastically from the change.
However, I am not sure about the affect of all kinds of queries. This might even slow down other searches.
> fix(performance): Reverse order of topological sorting in Gravsearch queries

- webapi/src/main/scala/org/knora/webapi/messages/util/ErrorHandlingMap.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchQueryOptimisation.scala
We are currently not actively working on removing a certain deprecation. Due to the massive amount of deprecation warnings we might miss/overlook warnings that really matter. Hence, remove our own deprecation annotations.
> chore: Remove @deprecation annotations

- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/SearchRouteV2.scala
Relates to DEV-2151
The removes metrics which are redundant since the introduction of `fuseki_request_duration` metric.
Collecting the metrics is removed in https://github.com/dasch-swiss/ops-deploy/pull/560
> chore: Remove duplicate 'gravsearch' metrics

- webapi/src/main/scala/org/knora/webapi/store/iiif/api/SipiService.scala
- webapi/src/main/scala/org/knora/webapi/store/iiif/impl/SipiServiceLive.scala
Spray json is able to parse `42.0` as an `Int`, zio-json is more strict fails, see also https://github.com/zio/zio-json/issues/1049. Hence, we have to add a custom decoder for `Int`.
> refactor: Replace spray json with zio-json for FileMetadataSipiResponse

- integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/store/cache/api/CacheService.scala
- webapi/src/main/scala/org/knora/webapi/store/cache/impl/CacheServiceInMemImpl.scala
> fix: Invalidate cached project information when adding an ontology to a project (DEV-2926)

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClientLiveSpec.scala
> refactor: Use sttpbackend and reuse access token if not expired

- .gitignore
- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- justfile
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/AdminApiEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/MaintenanceEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/PermissionsEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/api/ApiV2Endpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/api/DocsGenerator.scala
- webapi/src/main/scala/org/knora/webapi/slice/infrastructure/MetricsServer.scala
- webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/api/ResourceInfoEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/search/api/SearchEndpoints.scala
For now the open api documentation is only generated on demand by calling `just dog`.
This should enable @BalduinLandolt  and @mpro7 to integrate their newly migrated endpoints, so that in future we are able to:
1. Integrate all endpoints in the api
2. Create a new /docs endpoint in the dsp-api akin to the dsp-ingest
> feat: Add generating OpenApi yamls for the admin api

- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/Codecs.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpointsHandler.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/UsersADMRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/UsersRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/User.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/model/UserSpec.scala
This PR depends on https://github.com/dasch-swiss/dsp-api/pull/2996 being merged first.
Widen the allowed range of UserIris to account for existing iris in our database
* Allows for builtIn UserIris
* Regular UserIris start with `http://rdfh.ch/users/` and then an alphanumeric String containing `-` or `_` is allows, length >=4 and <=36 charaters
* Adds isBuiltInUser and isRegularUser extension methods to UserIri
* Moves creating a new UserIri from the StringFormatter to UserIri.makeNew
* Migrates the `DELETE admin/users/iri/{userIri}` route to tapir
> fix: Fix UserIri and allow existing values (DEV-3194)

- integration/src/test/scala/org/knora/webapi/routing/AuthenticatorSpec.scala
- webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
> fix: Less information in auth error messages (DEV-3260)

- docker-compose.yml
- project/Dependencies.scala
https://github.com/dasch-swiss/docker-apache-jena-fuseki/releases/tag/2.1.5
> chore: Update fuseki to latest release 2.1.5

- project/Dependencies.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/DateUtil.scala
Java's implementation uses an days starting at midnight, not at noon, thankfully. <sup>[JulianFields docs](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/JulianFields.html)</sup>
The tests seem to be good and failed when appropriate, so I have confidence in this change.
> chore: Remove jodd dependency (DEV-3069)

- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologySimple.jsonld
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologySimple.rdf
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologySimple.ttl
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.rdf
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.ttl
- webapi/src/main/resources/knora-ontologies/knora-base.ttl
- webapi/src/main/scala/org/knora/webapi/package.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
> fix: Remove cardinality restriction for comments on regions (DEV-3179)

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/User.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/model/UserSpec.scala
The user `images-reviewer-user` is failing Username validation leading to the `/admin/users` view not being available. There are more users with hyphens on both prods, so they'll now be allowed unless the db is cleaned up at some later point.
> fix: Allow hyphens in usernames (DEV-3306)

- docs/index.md
- mkdocs.yml
For https://docs.dasch.swiss/latest/DSP-API/ (in our combined docs setup - in an isolated setup, this corresponds to the `/` route) to be available, MkDocs needs a top level `index.md` file.
Issue Number: DEV-3345
> fix(docs): DSP-API docs root route gives a 404 error (DEV-3345)

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/KnoraProject.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/Vocabulary.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
- webapi/src/test/scala/org/knora/webapi/TestDataFactory.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/repo/KnoraProjectRepoInMemory.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMServiceSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLiveSpec.scala
> refactor: Add save to KnoraProjectRepo and use for setting the RestrictedView

- .github/workflows/create-release.yml
This should prevent to keep release PRs opened as ready for review for entire cycle.
> chore: Start release PRs as drafts

- webapi/src/main/resources/knora-ontologies/knora-base.ttl
- webapi/src/main/scala/org/knora/webapi/package.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
When using more than the built-in graphs the RepositoryUpdater fails to append data in the downloaded files.
Until this is resolved we need to disable the plugins and remain on knora-base version 28.
> fix: Disable broken upgrade plugins

- integration/src/test/scala/org/knora/webapi/core/ActorSystemTest.scala
- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- integration/src/test/scala/org/knora/webapi/testservices/TestClientService.scala
- webapi/src/main/scala/org/knora/webapi/core/ActorSystem.scala
- webapi/src/main/scala/org/knora/webapi/core/AppRouter.scala
- webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
- webapi/src/main/scala/org/knora/webapi/core/HttpServer.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/api/TapirToPekkoInterpreter.scala
> refactor: Simplify ActorSystem layer

- integration/src/test/scala/org/knora/webapi/routing/JwtServiceSpec.scala
- project/Dependencies.scala
- webapi/src/main/scala/org/knora/webapi/routing/JwtService.scala
> chore: Switch JWT library to use ZIO-JSON instead of Spray JSON

- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologySimple.jsonld
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- webapi/src/main/resources/knora-ontologies/knora-base.ttl
- webapi/src/main/scala/org/knora/webapi/package.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
> fix: Temporarily bring back support for `isSequenceOf` while it exists in data

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/AbstractEntityRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLive.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraUserRepoLive.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/repo/service/Repository.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/OntologyRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyRepoLive.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/model/AdministrativePermissionRepoSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/repo/KnoraProjectRepoInMemory.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLiveSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLiveSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/KnoraUserRepoLiveSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/common/repo/AbstractInMemoryCrudRepository.scala
- webapi/src/test/scala/org/knora/webapi/slice/common/repo/InMemoryCrudRepositorySpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/common/repo/service/AbstractInMemoryCrudRepository.scala
- webapi/src/test/scala/org/knora/webapi/slice/common/repo/service/InMemoryCrudRepositorySpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/repo/service/OntologyRepoLiveSpec.scala
- **refactor: Eliminate unnecessary conversions from Chunk to list by changing collection return types for repos to Chunk**
should be merged first: https://github.com/dasch-swiss/dsp-api/pull/3163
> refactor: Change return types for collections in repositories to Chunk

- .github/workflows/build-and-test.yml
- .github/workflows/publish-release.yml
> chore: Use buildjet instead of actuated

- integration/src/test/scala/org/knora/webapi/e2e/admin/GroupsADME2ESpec.scala
- integration/src/test/scala/org/knora/webapi/responders/admin/GroupsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/responders/IriService.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/GroupRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/GroupService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraGroupRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraGroupService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLive.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/api/service/AuthorizationRestServiceSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLiveSpec.scala
> refactor: Move creation Group from responder to services

- integration/src/test/scala/org/knora/webapi/responders/admin/GroupsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/GroupRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/GroupService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraGroupService.scala
> refactor: Move Group update from responder to services (DEV-3292) 

- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologySimple.jsonld
- test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
- webapi/src/main/resources/knora-ontologies/knora-base.ttl
- webapi/src/main/scala/org/knora/webapi/package.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
Issue Number: DEV-3505
This PR adds a number of properties to `knora-base:Segment` in hopes that most projects will find their needs satisfied by this, rather than needing subclasses of Segment with custom properties.  
For all of them, mappings to popular external ontologies have been added, in hope that this will be a step towards making data more interoperable; furthermore this backs up the claim that this is supposed to be a reasonable set of properties for the concept of segments.
> feat: Extend the model of `Segment` with additional properties (DEV-3505)

- integration/src/test/scala/org/knora/webapi/responders/admin/GroupsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/GroupRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/AdminDomainModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/GroupService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraGroupService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraUserRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraUserService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraUserRepoLive.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/api/service/AuthorizationRestServiceSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/GroupServiceSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLiveSpec.scala
Apart of moving update method also have been added:
- tests for `GroupService`,
- `KnoraGroupRepoLiveSpec` missing members implementation,
- methods that allow to cope with `KnoraGroup` instead of `Group` in `KnoraUserService`,
- `findByGroupMembership` method in `KnoraUserRepoLive`
> refactor: Move GroupStatus update from responder to services (DEV-3292)

- integration/src/test/scala/org/knora/webapi/responders/admin/GroupsResponderADMSpec.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/GroupRestService.scala
> refactor: Fix checks order in Group update method (DEV-3292)

- .github/actions/preparation/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/scala-steward.yml
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> chore: Update GitHub actions to support Node.js 20 instead of 16

- integration/src/test/scala/org/knora/webapi/models/filemodels/FileModels.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
> refactor: Remove unused trait IOValueV2

- webapi/src/main/scala/org/knora/webapi/slice/admin/api/AdminApiModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/MaintenanceEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/MaintenanceRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/AdminDomainModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/MaintenanceAction.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/maintenance/MaintenanceService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/maintenance/TopLeftCorrectionAction.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/api/service/MaintenanceServiceSpec.scala
This PR is mostly strictly refactoring: Moving code to separate file, etc. The most significant changes are:
- removal of an unused dependency (`PredicateObjectMapper`) and its transitive dependencies
- introducing a trait for maintenance actions (let me know if you find that useful at all!)
- using the actual string values of the path variables for the different maintenance actions endpoints as examples in the OpenAPI docs.
> refactor: Refine scaffolding for maintenance actions (DEV-3532)

- integration/src/test/scala/org/knora/webapi/it/v2/KnoraSipiIntegrationV2ITSpec.scala
- integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/AssetIngestedState.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
- webapi/src/main/scala/org/knora/webapi/routing/v2/ValuesRouteV2.scala
- webapi/src/test/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueContentV2Spec.scala
* Same mechanism skipping temp file removal for UpdateValueV2 as for CreateResource
* Also for CreateValueV2, but tests are missing for now, because I couldn't figure out where to add them
* Minor: refactored two lines `.exists` in the vicinity of pertaining changes
> feat: X-Asset-Ingested: skip Sipi temp move for updates (DEV-3504)

- integration/src/test/scala/org/knora/webapi/it/v2/KnoraSipiIntegrationV2ITSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/util/WithAsIs.scala
Refactoring changes are split per commits whose descriptions are (time ascending order):
* reuse header adding code, reuse jsonLdHttpEntity
* add WithAsIs(asOpt) and create assertingUnique
* actually use jsonLdHttpEntity everywhere
* def requestJsonLdWithAuth(request) = request with "~> addAuthorization"
* reuse URLencode + getResponseJsonLD inlining
* flatten some UploadFileRequest.make().toJsonLd calls
* import OntologyConstants._ and the resulting changes
* moving around a few things (diff: +10, -41)
Issues in tests discovered while working on DEV-3504.
> refactor: KnoraSipiIntegrationV2ITSpec simplifications (DEV-3504)

- webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponder.scala
- **Replace throw BadRequest with fail**
- **Replace throw BadRequest with fail**
- **simplify if else by using match**
- **remove duplicate scaladocs**
- **Re-add missing scaladoc**
- **Simplify shift code**
> refactor: Simplify shift code

- integration/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportServiceIT.scala
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala
Replaces `isGravsearch: Boolean` with a `SparqlTimeout` enum. Keeps queries with different timeout separated in our prometheus metrics.
> refactor: Introduce SparqlTimeOut, preparation to allow different timeouts for maintenance queries

- integration/src/test/scala/org/knora/sipi/SipiIT.scala
- sipi/scripts/authentication.lua
- sipi/scripts/file_info.lua
- sipi/scripts/sipi.init.lua
- sipi/scripts/util.lua
- webapi/src/main/scala/org/knora/webapi/slice/infrastructure/Scope.scala
Always allow access to resources in sipi if the access token is that of a system admin or project admin for the respective prefix. 
This is necessary for the preview in dsp-app after the upload.
> feat(sipi): Allow read all images for users with write:project:XXXX scope (DEV-2628)

- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/slice/infrastructure/api/ManagementEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/FusekiPaths.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
- webapi/src/test/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala
1. ~~@BalduinLandolt are the warn/debug info/warn changes required?~~
2. ~~Is `if (knoraBaseOntologyVersion != KnoraBaseVersion)` commented out for any particular purpose? Should I revert it?~~
The flag is disabled by default and I assume should be enabled for test envs in ops-deploy. It was tested both with false and true and was double checked to be false by default.
Issue Number: DEV-3703
> feat: Compaction endpoint, guarded (DEV-3703)

- build.sbt
- integration/src/test/resources/application.conf
- integration/src/test/scala/org/knora/webapi/E2EZSpec.scala
- integration/src/test/scala/org/knora/webapi/ProjectEraseIT.scala
- integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyFormatsE2ESpec.scala
- integration/src/test/scala/org/knora/webapi/e2ez/KnoraBaseJsonModels.scala
- integration/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/IntegrationTestListADMJsonProtocol.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraUserService.scala
- **test: Add ProjectEraseIT**
- **fixes sbt-header plugin being applied to integration/Test source**
Not all things have been tested yet. I am currently working on adding more tests, e.g.:
* Permissions
* Ontologies
* …
> chore: Add integration tests for erasing a project (DEV-3681)

- webapi/src/main/scala/org/knora/webapi/slice/SliceModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/AdminModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/AdminApiModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/AdminDomainModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/infrastructure/InfrastructureModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/security/SecurityModule.scala
This is just an idea to make the modules concept present in our slice packages.
Happy to discuss and extend this together with you.
> refactor: Introduce model for SliceModules

- integration/src/test/scala/org/knora/webapi/ProjectEraseIT.scala
- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/AdminDomainModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/DefaultObjectAccessPermissionRepo.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/AdministrativePermissionService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DefaultObjectAccessPermissionService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectEraseService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/RdfConversions.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/Vocabulary.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/DefaultObjectAccessPermissionRepoLive.scala
- **Inline OntologyResponderV2 trait and add test for deleting an ontology graph during project erasing**
- **Add test for administrative permissions**
- **Add test for daop cleanup**
> chore: Add integration tests for project erasure (DEV-3681)

- webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpointsHandler.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectEraseService.scala
If true the assets in ingest will be kept.
The motivation for this flag comes from from @jnussbaum who would only want to remove the api data and reuse already ingested assets for test runs [on one of the RDU servers](https://github.com/dasch-swiss/ops-deploy/pull/768/files).
> feat: Add 'keepAssets' query param to erase project endpoint

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/KnoraGroup.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/model/GroupIriSpec.scala
When a group IRI is invalid, include in the error message the IRI. This will help debugging an issue that today proved hard to investigate because the error message doesn't provide any information.
> chore: Add IRI to error message when a Group IRI is invalid.

- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
Right now, they all fall into the same bucket and the graph seems to have no meaning.
> fix: Smaller granularity for Grafana fuseki durations (DEV-3776)

- webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
Checked that the labels are now differentiated locally. The problem was == is really lax and just compares the object ids (or something). Cats' `===` would work, but then an `Eq` has to be derived and imported. The problem was `.timeout` wasn't added, so it was compared against an entirely different set of objects.
Second, now that the Grafana dashboard calculates the heatmaps correctly and bucket differences are pristine, I'm restoring the wide bucket range.
> fix: Fix query tracking tags (== is faulty), set previous bucket sizes (DEV-3776)

- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
Some of the very first Scala code I ever wrote... and it shows!
> refactor: Small refactoring

- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyTriplestoreHelpers.scala
- **Add feature flag**
- **Integrate feature flag**
- **Introduces `DISABLE_LAST_MODIFICATION_DATE_CHECK` environment variable, set to `true` in order to disable the check for all endpoints**
List of places where the LMD is checked:
In ResourceResponderV2:
* markResourceAsDeletedV2
* eraseResourceV2
* updateResourceMetadataV2
In OntologyResponderV2:
* changeGuiOrder
* changeOntologyMetadata
* deleteCardinalitiesFromClass
* changePropertyLabelsOrComments
* deleteOntologyComment
* changePropertyGuiElement
* addCardinalitiesToClass
* changeClassLabelsOrComments
* createProperty
* createClass
* canDeleteCardinalitiesFromClass
* checkLastModificationDateAndCanCardinalitiesBeSet
* deleteProperty
* deleteClassComment
* deleteOntology
* deletePropertyComment
* deleteClass
> feat: Add feature flag to disable lastModificationDate check (DEV-3870)

- integration/src/test/scala/org/knora/webapi/core/TestStartupUtils.scala
- integration/src/test/scala/org/knora/webapi/slice/lists/ListsV2E2Spec.scala
- webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
- webapi/src/main/scala/org/knora/webapi/slice/lists/api/ListsEndpointsV2Handler.scala
- webapi/src/main/scala/org/knora/webapi/slice/lists/domain/ListsService.scala
- **chore: Add e2e for `/v2/[node|list]/:listIri`, ensure that a 404 is returned in cases where the node is not a node and list is not a list**
Add test for the fix in https://github.com/dasch-swiss/dsp-api/pull/3314
> chore: Add e2e test for v2 lists endpoints

- webapi/src/main/scala/org/knora/webapi/slice/security/Authenticator.scala
Issue Number: DEV-3975
This was causing many false positive error logs on grafana
> fix: Do not log on error level when invalid credentials are provided (DEV-3975)

- webapi/src/main/scala/org/knora/webapi/slice/security/Authenticator.scala
- webapi/src/main/scala/org/knora/webapi/slice/security/api/AuthenticationEndpointsV2Handler.scala
Issue Number: DEV-4019
This PR fixxes the problem that when Fuseki is down and a client tries to authenticate, the API will return a `Bad Credentials` instead of `Internal Server Error` (breaking DSP-TOOLS' retry strategy).  
The cause is that the authenticator treats errors in finding the user the same as not finding them, which is a wrong assumption.  
This PR addresses this by using `die` for the actual errors and the `fail` channel for the not-found case. Alternatively, one could solve this with Optional/Either in the error channel. I'm open for discussion.
> fix: Respond with internal error instead of bad credentials when triplestore is down during authentication (DEV-4019)

- build.sbt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/gravsearch/getIncomingImageLinks.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/changeParentNode.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/checkListNodeExistsByName.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/deleteNode.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/deletePermission.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/getFileValue.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/getProjectOfEntity.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/updateNodePosition.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/updatePermission.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/changePropertyGuiElement.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/createProperty.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/deleteClass.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/deleteProperty.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/deleteValue.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/eraseResource.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/getAllOntologyMetadata.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/getAllResourcesInProjectPrequery.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/getResourcePropertiesAndValues.scala.txt
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/isEntityUsed.scala.txt
I've got annoyed by warns thrown by the complier therefore removed unused TWIRL imports.
Additionally silenced the false positive warnings coming from these templates which are not supported in Scala version we are using, but are again supported in Scala 3.5.0: https://github.com/scala/scala3/pull/18783
> chore: Remove unused imports from TWIRL templates and silence false positives

- integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/model/Cardinality.scala
- **Remove `appActor ! CreatePropertyRequestV2` and replace with method call on responder in `OntologyResponderSpecV2`**
> test: Remove CreatePropertyRequestV2 from OntologyResponderSpecV2

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/model/Cardinality.scala
This reverts commit ecc5a1ad815440c3549804872dac0860c60d0730.
This was unfortunately merged with https://github.com/dasch-swiss/dsp-api/pull/3354 which should only contain the refactoring but contained a revert of https://github.com/dasch-swiss/dsp-api/pull/3347
Initially I simply wanted to revert the fix before adding a test in order to make sure the test fails. But when opening the PR as refactoring only I then forgot to remove the revert of the fix.
> fix: During resource creation verify required cardinalities based on the provided values (DEV-4017) (#3347)"

- integration/src/test/scala/org/knora/webapi/config/AppConfigForTestContainersZSpec.scala
- integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
- integration/src/test/scala/org/knora/webapi/testcontainers/DspIngestTestContainer.scala
- integration/src/test/scala/org/knora/webapi/testcontainers/SharedVolumes.scala
Currently tests fails also on other PRs. I checked and it seems like the testcontainer for dsp-ingest failed to startup sometimes due to a race condition of how the temp directory was created inside. The temp dir is now mounted as a regular volume which fixes the problem.
> test: Fix testcontainer startup

- webapi/src/main/scala/org/knora/webapi/slice/shacl/api/ShaclApiService.scala
- webapi/src/main/scala/org/knora/webapi/slice/shacl/api/ShaclEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/shacl/domain/ShaclValidator.scala
- webapi/src/test/scala/org/knora/webapi/slice/shacl/api/ShaclApiServiceSpec.scala
- webapi/src/test/scala/org/knora/webapi/slice/shacl/domain/ShaclValidatorSpec.scala
The writing into the output stream must happen on a different thread than the reading from the input stream.
Additionally use a temp File for streaming the turtle from the request in order to reduce memory footprint.
> fix: Fix deadlock when streaming out the shacl validation report

- integration/src/test/scala/org/knora/webapi/responders/admin/PermissionsResponderSpec.scala
- integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponder.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
- **extract code to PermissionsResponder. getPropertiesDefaultPermissions to**
- **align method names (getDefaultValuePermissions -> getPropertyDefaultPermissions)**
- **use ProjectIri type for getPropertyDefaultPermissions**
- **use ProjectIri type for getPropertyDefaultPermissions and simplify code**
- **clarify PermissionResponder method naming for new Resource and Value creation**
> refactor: Simplify Value create code and use ProjectIri instead of String

- webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
> fix: Fix precedence of endpoints so that /v2/resources/info is routed to the ResourceInfoEndpointHandler

- .github/workflows/publish-docs.yml
Docs publish CI failed on main because the OpenAPI docs are not present - as they need to be generated.  
This requires a bit of setup (java, just, ...).
> docs: Fix docs publish CI failing on main

- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/MaintenanceRequests.scala
Fixes an occurence of a `StringIndexOutOfBoundsException`:
```
{"name":"org.knora.webapi.http.handler.KnoraExceptionHandler$","timestamp":"2024-12-10T16:05:57.392932872Z  ","level":"ERROR","thread":"zio-fiber-1856268975","message":"Unable to run route /v2/resources","cause":"Exception in thread \"zio-fiber-\" java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 0
\tat java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
\tat java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
\tat java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
\tat java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
\tat java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
\tat …
```
> fix: Dummy filenames may not contain a file extension, remove it only if it exists (DEV-4227)

- integration/src/test/scala/org/knora/webapi/it/v2/KnoraSipiAuthenticationITSpec.scala
- webapi/src/test/scala/org/knora/webapi/messages/v2/responder/ontologymessages/InputOntologyV2Spec.scala
> test: Migrate InputOntologyV2Spec to become a simple unit zio-test in the test source set

- integration/src/test/scala/org/knora/webapi/core/TestStartupUtils.scala
- integration/src/test/scala/org/knora/webapi/responders/v2/LoadOntologiesSpec.scala
- integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/StoreRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCache.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCacheFake.scala
Remove unused parameter and obsolete checks. Reloading ontologies in ontology cache does not require a requesting user.
> refactor: Remove user argument from reloading ontology cache

- .github/workflows/build-and-test.yml
- webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
- webapi/src/main/scala/org/knora/webapi/messages/ValuesValidator.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/model/OntologyName.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/model/OntologyNameSpec.scala
> feat: Clarify error message when creating an ontology with an invalid name

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/KnoraProject.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/jena/DatasetOps.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/jena/ModelOps.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologyV2RequestParser.scala
- webapi/src/test/scala/org/knora/webapi/slice/ontology/api/OntologyV2RequestParserSpec.scala
- **add failing test**
- **fix: Allow StringLiterals with language tag for properties when creating a class**
> fix: Allow StringLiterals with language tag for properties when creating a class (DEV-4555)

- webapi/src/main/scala/org/knora/webapi/slice/common/api/BaseEndpoints.scala
Basic Auth worked correctly when correct credentials are presented, this fixes the correct status code in case of invalid credentials.
> fix: Return 401 when basic auth credentials are invalid instead of failing with Internal Server Error (DEV-4585)

- webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpointsHandler.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectRestService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectEraseService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportService.scala
*Issue*
When importing a project that was previously exported, any data created after the export remains instead of being removed.
*Expected Behavior*
Importing a project should restore the exact state of the export, meaning any data added after the export should be removed.
Ensure that import exists before importing.
Erase the project before import.
Reload OntologyCache after import.
> fix: Erase the project before the import and refresh the ontology cache after import (DEV-4584)

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/LegalInfoModel.scala
> fix: Ensure that legal info String value objects are rendered as String in OpenApi yml (DEV-4695)

- webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/Pagination.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/LegalInfoModel.scala
Due to a bug in the yaml generator I am unable to provide the schema on the generic PagedResponse directly and hence we have to add it to each Value used in PagedResponse.
The bug we are affected by is https://github.com/softwaremill/tapir/issues/3922
> fix: Make data of our PagedResponses required in OpenAPI yaml

- integration/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
Deleting or erasing a resource have different preconditions.
Add check for in use when deleting the resource; the same way when erasing.
> fix: Align erasing and deleting Resources, prevent deletion of a resource if it is in use (DEV-4767)

- webapi/src/main/scala/dsp/errors/Errors.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/api/BaseEndpoints.scala
Before this fix the appropriate mapping was missing in Tapir and a 500 was returned.
> fix: When an EditConflictException is returned it is rendered as 400 Bad Request

- integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
- webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/eraseResource.scala.txt
Before erasing a `kb:Resource` we make sure that no other non-deleted Resource is referencing the one to be deleted with any non-deleted `kb:Value`.
In turn this means we are accepting deleted or previous versions of `kb:Values` may reference an IRI which does not exist anymore, aka. is a dangling reference.
The past practice of erasing `LinkValues` from other resources is not only dangerous and incomplete (as it does not take into account Standoff) - it also created an accidential complexity which is hard to understand. Hence this is removed.
> fix: Do not remove values from other `kb:Resource`s when erasing another `kb:Resource`

- webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectService.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/repo/rdf/Vocabulary.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/IriConverter.scala
- **fix: Allow to delete or erase a Resource only if no other non-delete Resource in the same project points to it // removes checking refs from Values**
I have been looking into Johannes Nussbaum's problem ([RDU-74](https://linear.app/dasch/issue/RDU-74/0806-webern-remove-class-publishing-house-from-data-model-on-prod)) together with Nora Ammann .
Essentially he wants to erase a resource but api prevents this.
```
{
"message": "Resource http://rdfh.ch/0806/_o3Ck2WsT-2qiJFmKTEqfQ cannot be erased, because it is referred to by another resource"
}
```
The error message of this response is misleading. Basically the check of "is referred to by another resource" is currently broken, in the sense that it also detects properties coming from deleted or previous versions of `knora-base:Value`s …
> fix: Allow to delete or erase a kb:Resource only if no other non-deleted kb:Resource in the same project points to it

- integration/src/test/resources/application.conf
- webapi/src/main/resources/application.conf
- webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/AdminModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/AdminDomainModule.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/LegalInfoService.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/LegalInfoServiceSpec.scala
The frontend does not yet implement the possibility to enable licenses, so that we have to be able to disable the check for now.
This PR makes it configurable per environment. Per default the license is only checked to be available but does not have to be enabled on the project where the `FileValue` was created.
> feat: Add feature flag for full license check during asset creation

- integration/src/test/scala/org/knora/webapi/store/triplestore/TriplestoreServiceLiveSpec.scala
- webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
- webapi/src/main/scala/org/knora/webapi/messages/util/rdf/SparqlSelectResult.scala
- webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/OntologyTriplestoreHelpers.scala
- webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
This PR removes the implicit filtering of empty strings from the result set returned by Fuseki.
The `TripelstoreService`, as the database access layer, should remain neutral regarding the validity of data values. Previously, it allowed writing empty strings to the database but silently excluded them when reading data back. This inconsistency introduced unexpected behavior and, in past cases, caused application failures — including instances where the application was unable to start.
By preserving empty strings in the query results, this change ensures consistent read/write behavior and delegates data validation responsibilities to the appropriate layers of the application.
> fix: Allow empty strings as results from the database (DEV-4887)

- integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
- integration/src/test/scala/org/knora/webapi/messages/admin/responder/IntegrationTestAdminJsonProtocol.scala
- integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/Examples.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsEndpointsRequestsAndResponses.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsMessagesADM.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/LegalInfoModel.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectService.scala
- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala
- webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectServiceSpec.scala
Add default `CopyrightHolder`s for AI and unknown cases.
Allow to provide `allowedCopyrightHolders` when creating a project.
Always add the default `CopyrightHolder`s to the `allowedCopyrightHolders` during project creation.
> feat: Add default CopyrightHolders when creating a new project (DEV-4929)

- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
- webapi/src/main/scala/org/knora/webapi/slice/common/KnoraIris.scala
- webapi/src/main/scala/org/knora/webapi/slice/resources/api/ResourcesEndpoints.scala
- webapi/src/main/scala/org/knora/webapi/slice/resources/api/ResourcesEndpointsHandler.scala
- webapi/src/main/scala/org/knora/webapi/slice/resources/api/model/Models.scala
- webapi/src/main/scala/org/knora/webapi/slice/resources/api/service/ResourcesRestService.scala
This is meant to be an experimental endpoint which is currently returning the metadata information as json.
It logs out the duration of the query, so that we can understand whether or not we need pagination.
Since this is just explorative I have not bothered to add any tests yet.
The produced query looks like this:
```sparql
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?classIri ?createdAt ?creator ?deletedAt ?label ?modifiedAt ?resourceIri
WHERE { 
GRAPH <http://www.knora.org/data/0803/incunabula> { 
?resourceIri a ?classIri ;
knora-base:creationDate ?createdAt ;
knora-base:attachedToUser ?creator ;
rdfs:label ?label .
OPTIONAL { ?resourceIri knora-base:lastModificationDate ?modifiedAt . }
OPTIONAL { …
```
> feat: Add experimental resource metadata endpoint

- integration/src/test/scala/org/knora/webapi/responders/v2/ValuesEraseSpec.scala
- webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
After realizing that `gravsearchV2` produces `ReadResourcesSequenceV2`, I found `getResourcesV2` which also does this, but with the added functionality of also showing deleted values.
It's not possible to query for previousValues in Gravsearch, because it requires having knora-base PREFIX, which is forbidden by Gravsearch.
Unfortunately the existing query cannot be used in all cases, as it starts breaking some integration tests, so instead of updating `def getResourceWithPropertyValues` I used `getResourcesV2` only in one place.
> feat: Allow hard-deleting soft-deleted values (DEV-4701)

- webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala
Changed log levels for asset information retrieval in `DspIngestClientLive`. Reduced the verbosity of logs by changing:
- The initial asset info log from `WARNING` to `INFO` level
- The response code and response body logs from `WARNING` to `DEBUG` level
This change ensures that normal operation logs don't clutter the warning log stream, while still maintaining appropriate visibility for asset information retrieval operations.
> chore: Use more reasonable log level

- webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
Added ordering by label to the SPARQL query for retrieving regions of a resource. The query now:
1. Includes the `rdfs` prefix for accessing label properties
2. Orders results by the region's label using `ORDER BY ?label`
3. Improves query formatting with consistent indentation for better readability
This change ensures that regions are returned in a consistent, alphabetical order based on their labels, making the results more predictable and easier to navigate for users.
> feat: Sort annotations by label (DEV-5220)

- integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
- justfile
- webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
The issue was caused by resource class validation logic in the eraseResourceV2 method that failed for deleted resources due to an API representation transformation.
The Problem Flow:
1. Resource Created: Original class (e.g., societe-savoie:ItemGroup)
2. Resource Deleted: Still has original class in triplestore, but marked with knora-base:isDeleted=true
3. Resource Retrieved for Erasure: getResourcePreviewV2 calls asDeletedResource() which transforms the class to knora-base:DeletedResource for API responses
4. Validation Failure: The erase operation compared:
- From triplestore: knora-base:DeletedResource (transformed representation)
- From client: societe-savoie:ItemGroup (original class in external schema)
- Expected internal: societe-savoie:ItemGroup (converted to internal schema)
- …
> fix: Erase a deleted resource

- modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/ResourcesEndpointsGetResourcesE2ESpec.scala
- modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- modules/testkit/src/main/scala/E2ESpec.scala
Move all tests for `GET /v2/resources/:resourceIri` to a dedicated file.
> refactor: Split ResourcesEndpointsE2ESpec, extract GET /v2/resources tests

- modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
- modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
- modules/testkit/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
- modules/testkit/src/main/scala/org/knora/webapi/testservices/TestResourcesApiClient.scala
- webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
Adds tests to ensure create resource and update value with comments with line breaks are working correctly.
Removes double encoding of comment.
Related to https://github.com/dasch-swiss/dsp-api/pull/3737
> fix: Fix double encoding of comments when creating a resource (DEV-5356)
