webapi/_test_data/demo_data/images-demo-data.ttl
webapi/_test_data/responders.v1.ValuesResponderV1Spec/incunabula-data.ttl
webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala

Fix errors in exported test/demo data:
* Fix invalid timestamps.
* Make standoffHasLink point to a resource, not to a `LinkValue`.

Fix timestamps and predicates in test/demo data.

---

webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/SipiResponderV1Spec.scala

fix(ontology responder): Include preferred language in ontology cache keys

---

salsah/src/public/js/03_showval.js
salsah/src/public/js/imagebase.js
webapi/src/main/resources/application.conf

First steps into integrating SALSAH with Knora

SALSAH Integration

---

salsah/src/public/default.css

- font color in infowin
- Resolves #156

fix (salsah): font color in infowin

---

webapi/src/main/resources/logback.xml
webapi/src/main/scala/org/knora/webapi/viewhandlers/ResourceHtmlView.scala
webapi/src/main/twirl/views/resource/properties.scala.html
webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1E2ESpec.scala

- f: hide preview image if no image supplied
- Resolves #154

Don't create image preview in 'Resources.html' route, if there is no image to show

---

webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala

Don't show resource classes that can't be instantiated

---

README.md

add internal link to doc/readme

add internal link to doc/readme

---

docs/Readme.md

- the workaround to get pip and pyvenv work is explained for those who use anaconda on Mac or Linux

type (docs):added remark about pyvenv for anaconda users on mac and linux

---

salsah/src/public/less/search.less

related to :
https://github.com/dhlab-basel/Knora/pull/191
Sorry @benjamingeer I only thought later about `less`.

relative paths

---

docs/rst/knora-api-server/api_v1/delete-resources-and-values.rst
salsah/src/typescript_interfaces/deleteResponseFormats.ts

Document deleteComment

---

webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala

fix (webapi): Handle request for nonexistent resource class.

---

webapi/src/it/scala/org/knora/webapi/ITSpec.scala
webapi/src/it/scala/org/knora/webapi/e2e/v1/SipiV1ITSpec.scala

I forgot to do this cleanup in #414, so here's another PR for it.

Clean up Knora-Sipi integration tests

---

salsah/src/public/js/imagebase.js

fixes #495
here you are @benjamingeer

removed the limit for label size

---

salsah/src/public/js/02_searchlist.js
salsah/src/public/js/imagebase.js

fixes #497 
172ca308937e868127bf541b1821763d424025a3 adds a default icon for the resource view window:
it places a blue question mark as default icon and let it be draggable.

add default icon on resource view window

---

docs/rst/knora-api-server/design-documentation/futures-with-akka.rst

Provides some documentation about how to use  `recover` on  `Future`.
Fixes #502.

docs (recover Futures)

---

salsah/src/public/js/jquery.htmleditor.js
salsah/src/public/js/jquery.searchbox.js

replacing a "&nbsp;" by its character

---

docs/rst/knora-api-server/api_v1/adding-resources.rst
webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/ValuesV1R2RSpec.scala

I forgot to adapt some of the docs and tests when I introduced the XML standoff handling.
Thx to Sascha Kaufmann, I detected these bugs on Friday
closes https://github.com/dhlab-basel/Knora/issues/540

remove obsolete JSON standoff members

---

webapi/src/main/scala/org/knora/webapi/responders/v1/StandoffResponderV1.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/StandoffV1R2RSpec.scala

throw an error when the user provides an invalid mapping Iri
@loicjaouen Could you please try to do the thing you did on this branch and see if you get an apt error message?

fix (invalid mapping Iri):

---

webapi/WebapiBuild.sbt
webapi/src/test/scala/org/knora/webapi/util/InputValidationSpec.scala

test url validation

---

knora-ontologies/knora-base.ttl
webapi/_test_data/ontologies/beol-onto.ttl
webapi/_test_data/ontologies/incunabula-onto.ttl
webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala

added some missing labels and comments in beol-onto

refactor (beol-onto): add missing labels and comments

---

webapi/src/main/scala/org/knora/webapi/util/DateUtilV1.scala
webapi/src/main/scala/org/knora/webapi/util/InputValidation.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala

This PR introduces some more tests for BCE date handling and some minor code refactoring.

refactor (era handling): use constants for era

---

webapi/src/main/resources/application.conf

Add better description for `default-rdf-data` and `rdf-data` in `application.conf`.
- resolves  #621

docs (webapi): add description

---

.travis.yml
salsah/src/main/resources/application.conf

Deactivate headless browser tests.

build (travis): deactivate browser tests

---

docs/rst/knora-api-server/api_v1/reading-and-searching-resources.rst
webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
webapi/src/main/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
webapi/src/main/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
webapi/src/test/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala

adds support for Boolean Value in extended search
TODO: I think the Salsah 1.5 does not fully support this yet in extended search form
closes #635

feature (extended search V1): support Boolean value

---

salsah/src/public/js/jquery.extsearch.js

must be empty

---

salsah/src/public/index.html
salsah/src/public/js/jquery.resadd.js

Fix/salsah 1.5 processing sign

---

salsah/src/public/js/jquery.dateobj.js

keeping date selection box on top of ckeditor

---

docs/rst/knora-api-server/api_v2/knora-iris.rst
webapi/_test_data/all_data/admin-data.ttl
webapi/_test_data/all_data/permissions-data.ttl
webapi/src/test/scala/org/knora/webapi/SharedPermissionsTestData.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/PermissionsResponderV1Spec.scala

- add unil and unibas ranges
- add list IRI
- update permission IRI
- update project IRI
- update group IRI

docs: update v2 IRI documentation

---

webapi/src/main/resources/application.conf
webapi/src/main/resources/logback.xml
webapi/src/main/scala/org/knora/webapi/KnoraExceptionHandler.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/storesmessages/StoresMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/ResponderManager.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/StoresResponderADM.scala
webapi/src/main/scala/org/knora/webapi/responders/package.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/StoreRouteADM.scala
webapi/src/test/resources/logback-test.xml

feature (webapi): admin api (part 5)

---

webapi/_test_data/all_data/anything-data.ttl
webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjects.scala
webapi/src/main/scala/org/knora/webapi/util/DateUtilV1.scala
webapi/src/main/scala/org/knora/webapi/util/DateUtilV2.scala
webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiDateValue.json
webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjects.json
webapi/src/test/resources/test-data/resourcesR2RV2/BookReiseInsHeiligeLand.jsonld
webapi/src/test/resources/test-data/resourcesR2RV2/ThingWithBCEDate.jsonld
webapi/src/test/resources/test-data/resourcesR2RV2/ThingWithBCEDate2.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksNotPublishedOnDate.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksPublishedAfterDate.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksPublishedAfterOrOnDate.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksPublishedBeforeDate.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksPublishedBeforeOrOnDate.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksPublishedBetweenDates.jsonld
webapi/src/test/resources/test-data/searchR2RV2/BooksPublishedOnDate.jsonld
webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptional.jsonld
webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2R2Spec.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala

is related to https://github.com/dhlab-basel/Salsah/pull/154

fix (V2 date) : return era of date

---

salsah/Dockerfile
webapi/Dockerfile

build (docker): add utf-8 environment variable

---

.travis.yml

- remove docker image building in the test stage
- fix docker image building in the publish stage

build (travis): fix docker image building

---

.gitignore
.travis.yml
docs/DocsBuild.sbt
docs/src/jekyll/index.md
docs/src/sphinx/00-release-notes/v1.4.0.rst
webapi/WebapiBuild.sbt

- add missing release notes entry
- change the link to knora-base documentation
- resolves #834

docs (webapi): add missing release notes entry

---

webapi/_test_data/all_data/beol-data.ttl

list nodes in beol-data.ttl point to root node of the whole list.

list nodes of BEOL subject index point to parent

---

docs/src/paradox/00-release-notes/v1.6.0.md
docs/src/paradox/03-apis/api-v2/query-language.md
webapi/_test_data/e2e.v2.SearchRouteV2R2RSpec/gravsearchtest1-admin.ttl
webapi/_test_data/e2e.v2.SearchRouteV2R2RSpec/gravsearchtest1-data.ttl
webapi/_test_data/e2e.v2.SearchRouteV2R2RSpec/gravsearchtest1-onto.ttl
webapi/src/main/scala/org/knora/webapi/util/search/v2/GravsearchParserV2.scala
webapi/src/test/resources/test-data/searchR2RV2/ProjectsWithOptionalPersonOrBiblio.jsonld
webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
webapi/src/test/scala/org/knora/webapi/util/search/v2/GravsearchParserV2Spec.scala

Resolves #138.
@gfoo Thanks for the test case. Does this do what you need?

Allow a nested block in an OPTIONAL in Gravsearch

---

webapi/_test_data/project_shortcodes.md

-  add UBKVP shortcode to the list

doc (webapi): add UBKVP shortcode to the list

---

.travis.yml
docs/src/paradox/07-sipi/setup-sipi-for-knora.md
sipi/README.md

- Update Sipi invocation command.
- Update docs.
- resolves #900

build (travis): change sipi docker command

---

webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/StandoffV1R2RSpec.scala
webapi/src/test/scala/org/knora/webapi/util/standoff/XMLToStandoffUtilSpec.scala

There was a bug in how the xpath expression to separate words was created.
resolves #903

Fix: Creation of xpath expression to insert word separator

---

.travis.yml
docs/src/jekyll/index.md

- fix rvm issue
- remove link to not existent salsah1 documentation
- resolves #923

build (travis): fix travis rvm problem

---

.travis.yml
docs/src/paradox/00-release-notes/v1.7.0.md
salsah1/SalsahBuild.sbt
webapi/scripts/graphdb-se-knora-prod-repository-config.ttl.tmpl
webapi/src/main/resources/application.conf
webapi/src/main/resources/logback.xml
webapi/src/main/scala/org/knora/webapi/KnoraService.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
webapi/src/test/resources/logback-test.xml
webapi/src/test/scala/org/knora/webapi/e2e/v1/UsersV1E2ESpec.scala

- raise timeouts in KnoraService so that the triplestore check has time to complete
- #968

fix (webapi): startup check does not detect running triplestore

---

README.md

YourKit is a great Java profiler, which is helping me to see what is happening inside our app. It is a commercial product with a not so cheap license. It is used by the Akka team. With this acknowledgment, we will get licenses for free.

doc (webapi): add yourkit acknowledgment

---

webapi/_test_data/all_data/admin-data.ttl
webapi/_test_data/all_data/biblio-data.ttl
webapi/_test_data/all_data/permissions-data.ttl
webapi/_test_data/ontologies/beol-onto.ttl
webapi/_test_data/ontologies/biblio-onto.ttl
webapi/_test_data/project_shortcodes.md
webapi/_test_data/test_route/texts/beol/testLetter/p0801-beol.xsd
webapi/_test_data/test_route/texts/beol/testLetter/p0801-biblio.xsd
webapi/scripts/graphdb-knora-prod-data.expect
webapi/scripts/graphdb-knora-test-data.expect
webapi/scripts/win-graphdb-knora-test-data.ttl
webapi/src/main/resources/application.conf
webapi/src/test/resources/test-data/ontologyR2RV2/allOntologyMetadata.jsonld
webapi/src/test/resources/test-data/ontologyR2RV2/allOntologyMetadata.rdf
webapi/src/test/resources/test-data/ontologyR2RV2/allOntologyMetadata.ttl
webapi/src/test/scala/org/knora/webapi/SharedOntologyTestDataADM.scala
webapi/src/test/scala/org/knora/webapi/SharedTestDataADM.scala
webapi/src/test/scala/org/knora/webapi/SharedTestDataV1.scala
webapi/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/ProjectsV1E2ESpec.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala
webapi/src/test/scala/org/knora/webapi/responders/v1/UsersResponderV1Spec.scala
webapi/src/test/scala/org/knora/webapi/util/StringFormatterSpec.scala

biblio project is removed, biblio ontology is part of beol project now
Fixes #992.

fix (remove Biblio project)

---

docker-compose.yml
docs/src/paradox/00-release-notes/v2.x.x.md
sipi/config/sipi.knora-docker-config.lua
sipi/config/sipi.knora-docker-it-config.lua
sipi/config/sipi.knora-docker-test-config.lua
sipi/docker-compose.yml

fix (docker) sipi config in docker compose

---

salsah1/src/public/js/jquery.propedit.js

here `$this` is not a good idea as it depends on the context

bug fix simpletext

---

salsah1/src/public/js/jquery.propedit.js

fixes #1012
result after the fix:

fix (salsah): check if there is a value before accessing it

---

webapi/_test_data/all_data/permissions-data.ttl

default view permissions to images

---

salsah1/Dockerfile
salsah2/Dockerfile
webapi/Dockerfile

- resolves #1029
- resolves #1031
- resolves #1032
- resolves #1033
- resolves #1034
- resolves #1035
- resolves #1036
- resolves #1037
- resolves #1038
- resolves #1039
- resolves #1040
- resolves #1041
- resolves #1042

build (docker): fix codacy issues

---

.travis.yml
docs/src/paradox/00-release-notes/v2.x.x.md
webapi/WebapiBuild.sbt
webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala
webapi/src/test/scala/org/knora/webapi/util/standoff/XMLToStandoffUtilSpec.scala

Fix standoff to XML conversion with nested empty tag

---

webapi/_test_data/project_shortcodes.md

Added short code for "Musikalisches Lexikon der Schweiz"

feature (webapi): add MLS shortcode

---

docs/src/paradox/00-release-notes/next.md
docs/src/paradox/01-introduction/data-formats.md
docs/src/paradox/01-introduction/standoff-rdf.md
docs/src/paradox/01-introduction/what-is-knora.md
docs/src/paradox/02-knora-ontologies/introduction.md
docs/src/paradox/02-knora-ontologies/knora-base.md
docs/src/paradox/03-apis/api-v1/adding-resources.md
docs/src/paradox/03-apis/api-v2/editing-resources.md
docs/src/paradox/03-apis/api-v2/knora-iris.md
docs/src/paradox/faq.md

Resolves #1045.
Resolves #1046.
Resolves #1061.

Update technical user docs

---

docker-compose.yml
docs/src/paradox/07-sipi/setup-sipi-for-knora.md
project/Dependencies.scala
sipi/config/sipi.init-knora.lua

build (knora): upgrade akka

---

KnoraBuild.sbt

build(knora): fix docker build

---

docs/src/paradox/05-internals/development/build-process.md

doc (knora): dockerComposeUp

---

webapi/src/main/scala/org/knora/webapi/Main.scala

fix (webapi): loading of ontologies on startup

---

webapi/_test_data/project_shortcodes.md

quick update of projects hosted in Lausanne

updating the list of shortcodes for projects hosted in Lausanne

---

webapi/_test_data/ontologies/anything-onto.ttl
webapi/src/main/resources/knoraXmlImport.xsd

Adds `knora-base:Region` to the XML schema for bulk import validation (as in #1171).

fix (bulk import): knora-base:Region as object class constraint

---

docs/src/paradox/00-release-notes/next.md
webapi/_test_data/responders.v2.OntologyResponderV2Spec/conflicting-cardinalities-onto.ttl
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala

Don't allow conflicting cardinalities

---

docs/src/paradox/03-apis/api-admin/users.md

docs: fix user admin api

---

docs/src/paradox/00-release-notes/next.md
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala

Unescape standoff string attributes when verifying text value update

---

webapi/src/main/scala/org/knora/webapi/routing/HealthRoute.scala

fix (webapi): message typo

---

project/build.properties

chore(knora): Update SBT version

---

webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala

fix(api-v1): Escape rdfs:label in bulk import

---

webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala

fix(api-v1): Fix double escaping of newline in bulk import

---

webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2SimpleTransformationRules.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala

fix(api-v2): Cache base class IRIs correctly when creating/updating class

---

webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2SimpleTransformationRules.scala
webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.jsonld
webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.rdf
webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.ttl

fix(api-v2): Fix typo

---

docs/Makefile
docs/src/api-v2/samples/resourcesResponses.ts

docs(api-v2): Fix sample responses

---

webapi/_test_data/all_data/anything-data.ttl
webapi/src/main/twirl/queries/sparql/admin/getFileValueGraphDB.scala.txt
webapi/src/main/twirl/queries/sparql/admin/getFileValueStandard.scala.txt
webapi/src/test/scala/org/knora/webapi/e2e/admin/SipiADME2ESpec.scala

fix(sipi): Allow Sipi to get permissions from Knora for a past file version

---

webapi/src/main/resources/logback.xml
webapi/src/main/scala/org/knora/webapi/KnoraService.scala
webapi/src/main/scala/org/knora/webapi/routing/AroundDirectives.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala

chore(webapi): add request duration logging

---

docs/src/paradox/06-salsah/index.md

otherwise it complains about not finding even aka

update to match sbt upper level config

---

docs/src/paradox/03-apis/api-admin/lists.md

doc (webapi): Add lists admin api

---

docker-compose.yml

fix(docker): missing redis container net config

---

docs/src/paradox/05-internals/design/api-v2/index.md
docs/src/paradox/05-internals/design/api-v2/query-design.md
docs/src/paradox/05-internals/design/principles/design-overview.md

docs(api-v2): Document how value versions are queried

---

.grenrc.js

chore: change gren config to issues

---

README.md

fix: build banner

---

KnoraBuild.sbt
Makefile
README.md

build: fix publish

---

webapi/src/main/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
webapi/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
webapi/src/test/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADMSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala

feat(webapi): add access to all users for project admin

---

.travis.yml
Makefile
README.md
docker/knora.docker-compose.yml
docs/src/paradox/04-publishing-deployment/getting-started.md
vars.mk

build(make): add graphdb home directory setting

---

sipi/scripts/convert_from_path.lua
webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiIntegrationV1ITSpec.scala
webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiScriptsV1ITSpec.scala
webapi/src/main/scala/org/knora/webapi/util/FileUtil.scala

Fix sipi integration test (ongoing)

---

webapi/src/main/scala/org/knora/webapi/routing/admin/ListsRouteADM.scala

fix(clientapi): Fix HTTP method in createChildNode function

---

salsah1/src/public/js/jquery.resadd.js

enable click on save button in case of recoverable error

---

salsah1/src/public/js/imagebase.js

fixed date string format

---

Makefile
vars.mk

Adds missing var to env (see https://github.com/dasch-swiss/knora-api/pull/1537)

Add missing env var

---

docs/src/paradox/03-apis/api-v2/query-language.md
docs/src/paradox/03-apis/api-v2/reading-and-searching-resources.md

fix complex schema url

---

docs/src/paradox/03-apis/api-v2/ontology-information.md

this PR does document #1622 but does not fix it :(

where to find last modif date?

---

.github/workflows/main.yml

build (ci): add node version

---

webapi/_test_data/all_data/anything-data.ttl
webapi/src/test/resources/test-data/searchR2RV2/ThingWithBoolean.jsonld
webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptionalOffset1.jsonld
webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOrDecimal.jsonld

fix(test): Fix typos in IRIs in anything-data.ttl

---

.github/workflows/main.yml

https://dasch.myjetbrains.com/youtrack/issue/DSP-196

Use node version 12 for knora api js lib tests

---

.github/workflows/main.yml
Makefile
webapi/src/main/scala/org/knora/webapi/SharedOntologyTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala

closes [DSP-229](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-29?issue=DSP-229)

generate test data for ontology operations

---

docs/src/paradox/03-apis/api-admin/lists.md
webapi/src/main/scala/org/knora/webapi/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ListsRouteADM.scala
webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala

Resolves [DSP-245](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-32?issue=DSP-245)

Create List with custom IRI

---

docs/src/paradox/03-apis/api-admin/lists.md
docs/src/paradox/03-apis/api-admin/projects.md
docs/src/paradox/03-apis/api-v2/editing-resources.md
docs/src/paradox/03-apis/api-v2/editing-values.md
docs/src/paradox/03-apis/api-v2/knora-iris.md
webapi/src/main/scala/org/knora/webapi/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala
webapi/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala

Resolves [DSP-242](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-32?issue=DSP-242)

Create a Project with Custom IRI

---

webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala

Resolves [DSP-416](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-32?issue=DSP-416)

test data for "create ontology response"

---

webapi/src/main/scala/org/knora/webapi/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala

https://dasch.myjetbrains.com/youtrack/issue/DSP-464

test(clientapi): Return dummy create ontology response

---

webapi/src/main/scala/org/knora/webapi/messages/util/OntologyUtil.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/InferringGravsearchTypeInspector.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2SimpleTransformationRules.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/InstanceChecker.scala
webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala

resolves [DSP-545](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-50?issue=DSP-545)

hierarchically ordered Sequence of base classes

---

webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala

https://dasch.myjetbrains.com/youtrack/issue/DSP-612

feat(api-v2): Add test data

---

docs/03-apis/api-v2/ontology-information.md
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/changeOntologyMetadata.scala.txt
webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala

resolves [DSP-610](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-52?issue=DSP-610)

update ontology metadata with a comment

---

.github/pull_request_template.md
webapi/src/test/resources/test.conf

resolves [DSP-702](https://dasch.myjetbrains.com/youtrack/issue/DSP-702)

DSP-702 Add template for PRs

---

third_party/dependencies.bzl

resolves [DSP-755](https://dasch.myjetbrains.com/youtrack/issue/DSP-755)

chore(build): Bump testcontainers version (DSP-755)

---

docs/03-apis/api-admin/permissions.md

resolves [DSP-754](https://dasch.myjetbrains.com/youtrack/issue/DSP-754)

PersmissionsDocs: remove the attribute

---

docs/05-internals/development/generating-client-test-data.md
webapi/scripts/expected-client-test-data.txt
webapi/scripts/update-expected-client-test-data.sh
webapi/src/test/scala/org/knora/webapi/e2e/HealthRouteE2ESpec.scala

resolves [DSP-816](https://dasch.myjetbrains.com/youtrack/issue/DSP-816)

DSP-816: Generate client test data for health route

---

webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/BUILD.bazel

resolves [DSP-470](https://dasch.myjetbrains.com/youtrack/issue/DSP-470)

DSP-470 Intermittent bind errors

---

.github/workflows/main.yml

DSP-877 Upload api-client-test-data to GitHub release

---

Makefile
third_party/versions.bzl

chore(build): Upgrade Sipi to 3.0.0-rc.8 (DSP-916)

---

.github/workflows/main.yml
docs/Readme.md

DSP-917 Releases pushed to Dockerhub from DSP-API are "dirty"

---

.github/workflows/main.yml
README.md
RELEASING.md
docs/04-publishing-deployment/publishing.md
docs/05-internals/development/docker-compose.md
docs/05-internals/development/graphdb.md
docs/05-internals/development/overview.md
docs/07-sipi/setup-sipi-for-knora.md
sipi/README.md

DSP-920 Renaming default github branch to "main" ;  Move to the same base branch

---

WORKSPACE
toolchains/BUILD.bazel

build: bazel workspace cleanup

---

.scalafmt.conf

style: Add Scalafmt config file

---

webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala

fix(standoffLinks): One hasStandoffLinkToValue per standoffLink given in the text (DSP-1254)

---

.github/workflows/main.yml

chore(gh-ci): update release please configuration (DSP-1382)

---

webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala

fix(ontology): Escape Special Characters in Ontology Comment (DSP-1406)

---

docs/03-apis/api-v1/reading-and-searching-resources.md
webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
webapi/src/test/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala

feature(ext search v1): add support for Geoname values (DSP-1493)

---

docs/03-apis/api-v1/reading-and-searching-resources.md
webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
webapi/src/test/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala

feat(ext search v1): add support for URI values (DSP-1522)

---

.bazelversion

chore: bumb Bazel to version with apple silicon support

---

docs/03-apis/api-v2/ontology-information.md
test_data/ontologyR2RV2/anythingOntologyWithValueObjects.ttl
test_data/ontologyR2RV2/anythingThingWithAllLanguages.ttl
test_data/ontologyR2RV2/boxOntologyWithValueObjects.ttl
test_data/ontologyR2RV2/imagesBild.ttl
test_data/ontologyR2RV2/incunabulaBook.ttl
test_data/ontologyR2RV2/incunabulaOntologySimple.ttl
test_data/ontologyR2RV2/incunabulaOntologyWithValueObjects.ttl
test_data/ontologyR2RV2/incunabulaPage.ttl
test_data/ontologyR2RV2/incunabulaPageAndBookWithValueObjects.ttl
test_data/ontologyR2RV2/knoraApiDateValue.ttl
test_data/ontologyR2RV2/knoraApiOntologySimple.ttl
test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.rdf
test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.ttl
test_data/ontologyR2RV2/standoffOntologyWithValueObjects.ttl
webapi/scripts/expected-client-test-data.txt
webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraBaseToApiV2ComplexTransformationRules.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/Responder.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala

feat(api-v2): Add routes for checking whether ontology entities can be changed (DSP-1621)

---

.bazelversion

chore(bazel): bump bazel version

---

webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala

fix(ontology): a system admin should be able to update an ontology (DSP-1621)

---

test_data/all_data/admin-data-minimal.ttl
test_data/all_data/permissions-data-minimal.ttl
webapi/scripts/fuseki-init-knora-test-minimal.sh

test: create minimal data test-setup (DSP-1728)

---

docs/03-apis/api-v2/editing-resources.md
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
webapi/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala

feat(resource-metadata): return resource metadata after metadata update request (DSP-1828)

---

webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
webapi/src/test/scala/org/knora/webapi/e2e/v1/AuthenticationV1E2ESpec.scala

fix(authentication): delete cookie (in chrome) on logout (DEV-325)

---

.bazelrc
.github/workflows/main.yml

chore(CI): add disk cache and other cleanup (DEV-388)

---

webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/SipiRouteADM.scala

Resolves DEV-634
Issue Number: DEV-634

refactor: improve logging (DEV-634)

---

docker-compose.yml

chore: fix docker containers timezone

---

webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala

fix(projectsADM): fix cache issue in getSingleProjectADM

---

project/Dependencies.scala

Resolves DEV-922
Issue Number: DEV-922

fix(authentication): Add bouncyCastle dependency (DEV-922)

---

.gitignore
Makefile

Resolves DEV-1038
Issue Number: DEV-1038

test: Add Make command to load test data locally (DEV-1038)

---

webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala

fix: fix RepositoryUpdater by removing old way of adding plugins (DEV-1057)

---

webapi/src/test/scala/org/knora/webapi/it/v2/KnoraSipiIntegrationV2ITSpec.scala

chore: temporarily ignore KnoraSipiIntegrationV2ITSpec

---

.github/workflows/dependency-graph.yml
.github/workflows/scala-steward.yml

build: add dependency checking

---

docs/01-introduction/file-formats.md
sipi/scripts/file_info.lua

docs: update file formats

---

.github/workflows/main.yml

build: add codacy coverage reporter

---

.github/workflows/main.yml

build: add coverage upload to codecov

---

.github/actions/cleanup/action.yml
.github/actions/preparation/action.yml
.github/pull_request_template.md

Resolves DEV-1313
Issue Number: DEV-1313

chore: Adjust GitHub template (DEV-1313)

---

.github/workflows/build-and-test.yml

chore: Ignore certain branches from tests (DEV-1112)

---

.scalafmt.conf
project/Dependencies.scala
webapi/src/main/scala/org/knora/webapi/Main.scala

chore: update dependencies

---

webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceHttpConnectorImpl.scala

fix: Increase timeout when emptying repository (DEV-1506)

---

.github/workflows/publish-release.yml

chore: make possible to run Publish GH Action manually (DEV-1519)

---

test_data/all_data/anything-data.ttl

Fix typo in test_data anything

---

docker-compose.yml

Adds the dsp-app container to the docker-compose file so that it can be startet in the dev environment.

feat (docker-compose.yml): Add dsp-app to docker-compose

---

.github/pull_request_template.md

Slightly improve/beautify the PR template.
Please check if your PR fulfils the following requirements:

chore: slight improvements to PR template

---

.github/workflows/build-and-test.yml
webapi/src/test/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraCardinalityInfoIsStricterThanZSpec.scala

Add a github action which renders the unit test result into human readable results for easier analysis should one test fail.
Issue Number: [DEV-1544](https://dasch.atlassian.net/browse/DEV-1544)

chore: Add dorny/test-reporter for webapi test results DEV-1544

---

.github/workflows/build-and-test.yml

Add a integration test report to our github pipeline.
See here for a run of this branch: https://github.com/dasch-swiss/dsp-api/actions/runs/3637083037/jobs/6138196968
Closes DEV-1544

chore: Add test report generation for integration tests (DEV-1544)

---

webapi/src/main/scala/org/knora/webapi/routing/admin/StoreRouteADM.scala

`GET /admin/stores` route stub has never been implemented and ever only returned "Hello World". I removed it now.

chore: remove unused route GET /admin/stores

---

dsp-shared/src/main/scala/dsp/valueobjects/Iri.scala
dsp-shared/src/main/scala/dsp/valueobjects/Project.scala
dsp-shared/src/main/scala/dsp/valueobjects/V2.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsPayloadsADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/RestProjectsService.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala

feat: expose POST /admin/projects as ZIO HTTP route (DEV-1587)

---

sipi/scripts/file_info.lua

Sipi creates images of mimetype image/jpx. Although this is currently not considered as well suited for longterm preservation by the community (BAR, KOST etc.), we should support it for obvious reasons.

feat: Add mimetype image/jpx as accepted

---

docker-compose.yml

chore: Expose the zio-http port in docker-compose.yml for the frontend (DEV-1482)

---

.github/workflows/publish-from-branch.yml

chore: fix manual release form branch (DEV-1519)

---

project/Dependencies.scala
webapi/src/main/scala/org/knora/webapi/core/HttpServerZ.scala
webapi/src/main/scala/org/knora/webapi/core/InstrumentationHttpServer.scala
webapi/src/main/scala/org/knora/webapi/http/handler/ExceptionHandlerZ.scala
webapi/src/main/scala/org/knora/webapi/http/middleware/AuthenticationMiddleware.scala
webapi/src/main/scala/org/knora/webapi/http/status/ApiStatusCodesZ.scala
webapi/src/main/scala/org/knora/webapi/instrumentation/health/HealthRouteZ.scala
webapi/src/main/scala/org/knora/webapi/instrumentation/index/IndexApp.scala
webapi/src/main/scala/org/knora/webapi/instrumentation/prometheus/PrometheusApp.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/AuthenticatorService.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/AuthenticatorServiceLive.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/api/ResourceInfoRoute.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/api/RestResourceInfoService.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/api/RestResourceInfoServiceLive.scala
webapi/src/test/scala/org/knora/webapi/http/middleware/AuthenticationMiddlewareSpec.scala
webapi/src/test/scala/org/knora/webapi/routing/admin/AuthenticatorServiceLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/resourceinfo/api/LiveRestResourceInfoServiceSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/resourceinfo/api/ResourceInfoRouteSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/resourceinfo/api/RestResourceInfoServiceSpy.scala

chore: switch zio http implementation from d11 to dev.zio

---

docs/03-endpoints/api-v2/reading-and-searching-resources.md
test_data/all_data/books-data.ttl
webapi/src/it/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala

fix: Search by label returns an Error when searching with a slash (DEV-1656)

---

webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlTransformer.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/Cache.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/CardinalityHandler.scala

* Rename OntologyCacheData.classToSuperClassLookup
* Rename OntologyCacheData.classToSubclassLookup
* Improve scaladoc: typo/references
* remove unnecessary braces/parenthesis
* reduce visibility of methods which can be private
* replace unnecessary partial function with anonymous function
* remove unused private field in Cache

refactor: cleanup Cache class, ie. scaladoc, renaming, code improvements

---

.scalafmt.conf
project/Dependencies.scala

chore(deps): update scalafmt-core, kamon-core, kamon-scala-future

---

.github/workflows/scala-steward.yml

This PR changes the schedule of dependency updates check from weekly to twice in a month.

chore(deps): change schedule of dependency updates check

---

project/Dependencies.scala

https://github.com/dasch-swiss/dsp-api/security/dependabot/12

chore: update Scala to 2.13.10

---

docs/02-dsp-ontologies/knora-base.md
docs/03-endpoints/api-v2/ontology-information.md
webapi/src/it/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyLegacyRepo.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/PredicateRepository.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/PredicateRepositoryLive.scala
webapi/src/main/scala/org/knora/webapi/util/EitherUtil.scala
webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/OntologyCacheDataBuilder.scala
webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/service/PredicateRepositoryLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/resourceinfo/api/IriConverterLiveSpec.scala

closes: DEV-1564 & DEV-1563
* Adds documentation for added and updated endpoints.
* Renames `ReplaceClassCardinalitiesRequestV2`
* Adds missing copyright headers

docs: replace/canset cardinality documentation (DEV-1564 & DEV-1563)

---

webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsService.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceMock.scala
webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala

feat: expose GET /admin/projects/[ iri | shortname | shortcode ]/{iri | shortname | shortcode }/admin-members as ZIO HTTP route (DEV-1587)

---

webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsService.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceMock.scala
webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala

feat: expose GET /admin/projects/Keywords as ZIO HTTP route (DEV-1587) 

---

webapi/src/main/scala/org/knora/webapi/Main.scala
webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
webapi/src/main/scala/org/knora/webapi/core/InstrumentationServer.scala

closes: DEV-1639
* Simplify setup of  `Main` and `nstrumentationServer` - I am not entirely sure what the problem was. However with this simplification at least locally I do get JVM metrics reliably.
* Fix logging to always use slf4j by horizontally composing the log layers before starting up the `DspEnvironmentLive`.

fix: fix JVM metrics and logging DEV-1639

---

webapi/src/it/scala/org/knora/webapi/TestDataFactory.scala
webapi/src/it/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsService.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
webapi/src/test/scala/org/knora/webapi/TestDataFactory.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala

Small clean-up task after having ported the `projects` routes to ZIO HTTP. A test data factory has been added to the integration tests, too.

refactor: Clean-up ZIO HTTP routes and related code

---

webapi/src/main/scala/org/knora/webapi/core/HttpServerZ.scala

Using the default `anyMethod` parameter doesn't work for PUT or DELETE requests. This PR explicitly assigns which CORS methods are allowed.

fix(CORS): explicitly assign allowed CORS methods

---

docs/03-endpoints/instrumentation/metrics.md
webapi/src/main/scala/org/knora/webapi/core/HttpServerZ.scala

chore(instrumentation): expose ZIO-HTTP metrics (DEV-1714)

---

project/Dependencies.scala
sipi/scripts/sipi.init.lua

Issue Number: DEV-1727
The new SIPI version adds pre-flight calls for non-image files. These have to be by-passed for now, until certain research projects have a solution for permission handling.

chore: update SIPI version and adjust Lua scripts (DEV-1727)

---

webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsService.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsResponderADMMock.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala

Issue Number: DEV-1728
* Replace `ActorToZioBridge` with zio based `ProjectsResponderADM` trait in `ProjectsService`

refactor: Integrate zio-fied project responder in zio route DEV-1728

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/groupsmessages/GroupsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala

refactor:  ziofy GroupsResponderADM DEV-1737

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala

refactor: ziofy UsersResponderADM DEV-1742

---

project/Dependencies.scala
webapi/src/main/resources/logback.xml
webapi/src/main/scala/org/knora/webapi/core/HttpServerZ.scala
webapi/src/main/scala/org/knora/webapi/http/middleware/AuthenticationMiddleware.scala

chore: log request and user ID as log annotations (DEV-1233)

---

webapi/src/it/scala/org/knora/webapi/CoreSpec.scala
webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/it/scala/org/knora/webapi/responders/admin/PermissionsResponderADMSpec.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala

refactor: ziofy PermissionsResponderADM  DEV-1739

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/sipimessages/SipiMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala

refactor: ziofy SipiResponderADM DEV-1740

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/ckanmessages/CkanMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/CkanResponderV1.scala

refactor: ziofy CkanResponderV1  (DEV-1743)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/ontologymessages/OntologyMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala

refactor: ziofy OntologyResponderV1 (DEV-1745)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala

refactor: ziofy ListsResponderADM (DEV-1738)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/projectmessages/ProjectMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ProjectsResponderV1.scala

refactor: ziofy ProjectsResponderV1 (DEV-1746)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/usermessages/UserMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/UsersResponderV1.scala

refactor: ziofy UsersResponderV1 (DEV-1750)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/listsmessages/ListsMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ListsResponderV2.scala

refactor: ziofy ListsResponderV2 (DEV-1752)

---

docs/03-endpoints/api-v2/ontology-information.md

docs: add missing documentation (DEV-1422)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/it/scala/org/knora/webapi/messages/util/standoff/StandoffTagUtilV2Spec.scala
webapi/src/main/scala/org/knora/webapi/core/AppRouter.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/util/ConstructResponseUtilV2.scala
webapi/src/main/scala/org/knora/webapi/messages/util/ValueUtilV1.scala
webapi/src/main/scala/org/knora/webapi/messages/util/standoff/StandoffTagUtilV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/StandoffResponderV2.scala

refactor: ziofy StandoffTagUtilV2 (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/searchmessages/SearchMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala

refactor: ziofy SearchResponderV1 (DEV-1748)

---

webapi/src/it/scala/org/knora/webapi/CoreSpec.scala
webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/it/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala
webapi/src/main/scala/org/knora/webapi/core/AppRouter.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/util/ValueUtilV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala

refactor: ziofy ValueUtilV1 (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/it/scala/org/knora/webapi/responders/v2/ResourceUtilV2Spec.scala
webapi/src/main/scala/org/knora/webapi/core/AppRouter.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/util/PermissionUtilADM.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala

refactor: ziofy ResourceUtilV2 & PermissionUtilADM (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/standoffmessages/StandoffMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/StandoffResponderV1.scala

refactor: ziofy StandoffResponderV1 (DEV-1749)

---

webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/countPropertyUsedWithClass.scala.txt
webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/service/PredicateRepositoryLiveSpec.scala

fix: Filter out deleted subjects and objects when counting for cardinalities (DEV-1795)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/it/scala/org/knora/webapi/responders/v2/ontology/CardinalitiesSpec.scala
webapi/src/main/scala/org/knora/webapi/core/AppRouter.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/Cache.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/CardinalityHandler.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyHelpers.scala

refactor: ziofy CardinalityHandler and OntologyHelpers (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/core/TestStartupUtils.scala
webapi/src/it/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLiveZSpec.scala
webapi/src/main/scala/org/knora/webapi/core/AppServer.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/repo/ResourceInfoRepoLive.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdater.scala
webapi/src/test/scala/org/knora/webapi/store/triplestore/TestDatasetBuilder.scala

refactor: remove zio die from triplestore (NO-TICKET)

---

webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala

fix: Invalidate the cache when changing the password (DEV-1814)

---

webapi/src/main/scala/org/knora/webapi/util/Logger.scala

chore: add logger name to text logging (DEV-1826)

---

webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/CardinalityService.scala
webapi/src/test/scala/org/knora/webapi/slice/ontology/domain/CardinalityServiceLiveSpec.scala

feat: Add all instances which violate the new cardinality to response (DEV-1861)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/resourcemessages/ResourceMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala

refactor: ziofy ResourcesResponderV1 (DEV-1747)

---

webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala

fix: Slow Gravsearch Queries are not being logged (DEV-1838)

---

webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala

When checking the logs a lot of entries are cluttering the view to important information which look like this:
```
INFO o.k.w.routing.admin.ProjectsRouteADM - All projects requested.
```
Remove this info logging.

chore: Remove needless logging of all requests to /admin/projects (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/actors/RoutingActor.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala

refactor: ziofy ValuesResponderV2 (DEV-1757)

---

webapi/src/main/scala/org/knora/webapi/responders/Responder.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ListsRouteV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/SearchRouteV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/StandoffRouteV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ValuesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/util/ActorUtil.scala

refactor: ziofy ResourceUtilV2 (DEV-1963)

---

.github/workflows/docker-publish.yml
Makefile

Issue Number: DEV-1848
Also reduce loglevel when running make targets for docker container from error to info.
https://github.com/sbt/sbt-native-packager/issues/1371

chore: Remove publishing sipi docker image because this build is broken (DEV-1848)

---

docs/05-internals/design/api-v2/gravsearch.md

fix typo in gravsearch docs

---

build.sbt
webapi/scripts/healthcheck.sh

Issue Number: [INFRA-93](https://linear.app/dasch/issue/INFRA-93/reboot-docker-container-if-dsp-api-is-crashed)
This change allows the container to detect when it is unhealthy and restart automatically in case the API is no longer responding or fatally unhealthy.
[INFRA-93]: https://dasch.atlassian.net/browse/INFRA-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add docker container healthcheck for dsp-api (INFRA-93)

---

webapi/src/main/resources/application.conf
webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
webapi/src/main/scala/org/knora/webapi/core/HttpServerZ.scala

chore: remove CORS restriction from ZIO-HTTP routes (DEV-2015)

---

webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV1.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/UsersRouteV1.scala

refactor: ziofy UserRouteV1 (DEV-2028)

---

webapi/src/it/scala/org/knora/webapi/e2e/v2/ontology/CardinalitiesV2E2ESpec.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCache.scala

fix: cardinality issues on subclasses after adding cardinalities to superclass (DEV-2026)

---

dsp-shared/src/main/scala/dsp/errors/Errors.scala
webapi/src/it/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
webapi/src/it/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryTransformerSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala

fix: Gravsearch wrongly finds no results, if a query can be optimized down to only negations (DEV-1980)

---

webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/ProjectsRouteV1.scala

refactor: remove throwing in V1 Projects Route (DEV-2037)

---

webapi/src/it/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/searchmessages/SearchMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/SearchRouteV1.scala

refactor: remove throws from V1 Search Responder(DEV-2038)

---

project/Dependencies.scala

chore: upgrade Sipi base image to 2.8.1 DEV-2019

---

.github/workflows/docker-publish.yml

chore: publish sipi images on each commit on main (DEV-1997)

---

.github/workflows/docker-publish.yml

Fixes docker-publish workflow failing.

chore: fix docker-publish workflow output step failing

---

Makefile

One more small fix to enable automatic deployment :)

chore: fix string returned by docker-image-tag containing special control characters

---

webapi/src/main/scala/org/knora/webapi/util/Logger.scala

chore: Remove warnings by using non deprecated zio.logging functions

---

docs/03-endpoints/api-v2/ontology-information.md

docs: Add subproperty documentation to the cardinalities check (DEV-2039)

---

webapi/src/it/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToCountPrequeryTransformerSpec.scala
webapi/src/it/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformerSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/MainQueryResultProcessor.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/mainquery/GravsearchMainQueryGenerator.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToCountPrequeryTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformer.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala

refactor: rename gravsearch utils (DEV-2074)

---

webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlTransformer.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala

refactor: remove intermediate interfaces from query transformers (DEV-2077)

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToCountPrequeryTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/InferenceOptimizationService.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala

refactor: remove more intermediate interfaces (DEV-2078)

---

webapi/src/main/scala/org/knora/webapi/messages/StandoffStuff.scala
webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
webapi/src/main/scala/org/knora/webapi/messages/XmlPatterns.scala
webapi/src/main/scala/org/knora/webapi/messages/util/ValueUtilV1.scala
webapi/src/main/scala/org/knora/webapi/messages/util/standoff/StandoffStringUtil.scala
webapi/src/main/scala/org/knora/webapi/messages/util/standoff/StandoffTagUtilV2.scala
webapi/src/main/scala/org/knora/webapi/messages/v1/responder/valuemessages/ValueMessagesV1.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilADM.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV1.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilZ.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/lists/GetListItemsRouteADM.scala

Devolped in a pairing session and based on https://github.com/dasch-swiss/dsp-api/pull/2585 <- merge this first

refactor: Extract standoff related functions from StringFormatter (NO-TICKET)

---

sipi/scripts/export-moving-image-frames.sh
sipi/scripts/upload_for_processing.lua

There were some issues / warnings from a linter used in the DSP-TOOLS repository for the export-moving-images-frames.sh script. They are dealt with in this PR.

refactor: improve export-moving-images-frames

---

webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/it/scala/org/knora/webapi/messages/util/search/SparqlTransformerSpec.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/QueryTraverser.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/GravsearchToPrequeryTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/ConstructToConstructTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/SelectToSelectTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/SparqlTransformer.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/types/GravsearchTypeInspectionUtil.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala

refactor: move Gravsearch SPARQL transformers to separate package

---

webapi/src/it/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
webapi/src/it/scala/org/knora/webapi/e2e/v2/JSONLDHandlingV2R2RSpec.scala
webapi/src/it/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
webapi/src/it/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
webapi/src/it/scala/org/knora/webapi/testservices/TestClientService.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/domain/IriConverter.scala

refactor: ziofy ResourcesRouteV2 (DEV-2091)

---

webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/SparqlTransformer.scala

No functional changes, just streamlining the inference process, so that future refactorings will be easier.

refactor: streamline SPARQL transformation

---

webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV1.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/ValuesRouteV1.scala

refactor: ziofy RouteUtilV1 and change deprecated code (DEV-2079)

---

webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsPayloadsADM.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/GroupsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala

* Remove KnoraRoute from ProjectRouteADM
* Replace RouteADMUtil function for random uuid with RouteZ.randomUuid()
* Move factory methods for ProjectUpdatePayloadADM and ProjectCreatePayloadADM into companion object

refactor: ziofy ProjectRouteADM (DEV-2104)

---

webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala

Extract methods from UpdateResourceMetadataRequestV2#fromJsonLD

refactor: Extract methods from UpdateResourceMetadataRequestV2#fromJsonLD (NO-TICKET)

---

webapi/src/main/scala/org/knora/webapi/responders/v1/ProjectsResponderV1.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/UsersResponderV1.scala

refactor: remove throws from UsersResponderV1 (DEV-2102)

---

sipi/scripts/migrate_files_into_new_structure.lua
sipi/scripts/util.lua

fix: Use copy instead of move for Sipi file migration

---

webapi/src/main/scala/org/knora/webapi/routing/admin/FilesRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/GroupsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/lists/CreateListItemsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/lists/GetListItemsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/lists/UpdateListItemsRouteADM.scala

refactor: remove throws from ADM routes (DEV-2137)

---

Makefile

chore: streamline db initialization make commands

---

webapi/src/main/scala/org/knora/webapi/routing/v2/SearchRouteV2.scala

Issue Number: DEV-2150
The metrics are not yet perfect but I'd like to test them on dev so it would be good to get this merged.

chore: add basic metrics to gravsearch routes (DEV-2150)

---

webapi/src/main/scala/org/knora/webapi/routing/v2/SearchRouteV2.scala

This PR does 2 things:
1. it improves the already reported gravsearch metrics (histogram)
2. it adds a different metric (summary) to see if this works better/worse on datadog

chore: add more gravsearch metrics

---

build.sbt

Relaxes the SIPI docker container healthcheck to prevent restarts during uploads.
Issue Number: INFRA-282

chore(sipi): increase healthcheck timeout and retries

---

webapi/src/it/scala/org/knora/sipi/SipiIT.scala

* Add more tests for iiif endpoint
* Refactor `SipiIT` to split suites by endpoints

test: add more tests for Sipi responses (NO-TICKET)

---

.scalafmt.conf
project/Dependencies.scala

Update dependencies (#2694)

---

docker-compose.yml

chore: Add dsp-ingest to docker-compose.yml 

---

sipi/scripts/authentication.lua

Temporarily add log lines for debugging purposes on dev.

chore: Add some logging to Sipi

---

.gitignore
docker-compose.yml
docs/04-publishing-deployment/configuration.md
webapi/src/it/scala/org/knora/webapi/config/AppConfigForTestContainers.scala
webapi/src/it/scala/org/knora/webapi/core/LayersTest.scala
webapi/src/main/resources/application.conf
webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
webapi/src/test/scala/org/knora/webapi/config/AppConfigSpec.scala

* Introduce JwtConfig and move jwt settings to it
* Add issuer and dsp-ingest audience to JwtConfig
* Expose JwtConfig as own Layer
* Add dsp-ingest to docker-compose.yml
* Remove dead code
* Update documentation

Refactor: Introduce JwtConfig and expose as layer

---

webapi/src/it/scala/org/knora/webapi/ITTestDataFactory.scala
webapi/src/it/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
webapi/src/it/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportServiceIT.scala
webapi/src/main/scala/dsp/valueobjects/Id.scala
webapi/src/main/scala/dsp/valueobjects/Project.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsPayloadsADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/KnoraProject.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportStorageService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
webapi/src/main/scala/org/knora/webapi/store/cache/impl/CacheServiceInMemImpl.scala
webapi/src/test/scala/dsp/valueobjects/IdSpec.scala
webapi/src/test/scala/dsp/valueobjects/ProjectSpec.scala
webapi/src/test/scala/org/knora/webapi/TestDataFactory.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/repo/service/KnoraProjectRepoInMemory.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClientMock.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectRepoInMemory.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMServiceSpec.scala

refactor: Rename Shortcode everywhere and use its type in KnoraProject property (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/ITTestDataFactory.scala
webapi/src/it/scala/org/knora/webapi/e2e/v1/ProjectsV1E2ESpec.scala
webapi/src/it/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
webapi/src/main/scala/dsp/valueobjects/Project.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsPayloadsADM.scala
webapi/src/main/scala/org/knora/webapi/responders/v1/ProjectsResponderV1.scala
webapi/src/main/scala/org/knora/webapi/routing/v1/ProjectsRouteV1.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportStorageService.scala
webapi/src/main/scala/org/knora/webapi/store/cache/impl/CacheServiceInMemImpl.scala
webapi/src/test/scala/dsp/valueobjects/ProjectSpec.scala
webapi/src/test/scala/org/knora/webapi/TestDataFactory.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectsServiceLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/routing/admin/ProjectsRouteZSpec.scala

refactor: standarise shortname naming (NO-TICKET)

---

webapi/src/it/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
webapi/src/main/scala/org/knora/webapi/responders/IriService.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/CardinalityService.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/isEntityUsed.scala.txt
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/isEntityUsed.scala.txt

refactor: optimize isEntityInUse queries, use ASK

---

webapi/src/it/scala/org/knora/webapi/responders/v2/ListsResponderV2Spec.scala

Remove incunable from ListsResponderV2Spec

---

webapi/src/it/scala/org/knora/sipi/SipiIT.scala

test: fix expired token in SIPI test

---

webapi/src/it/scala/org/knora/sipi/SipiIT.scala
webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala

test: Use JwtService to generate a jwt in SipiIT

---

knora-ontologies/knora-base.ttl
webapi/src/it/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR2710Spec.scala
webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR2710.scala

normalize whitespace in transformation

---

webapi/src/main/scala/org/knora/webapi/routing/RouteUtilADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteZ.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectExportResponse.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
webapi/src/test/scala/org/knora/webapi/responders/admin/ProjectADMRestServiceMock.scala

Make project export async

---

webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala

Add logging

---

build.sbt
integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
project/Dependencies.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilZ.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ValuesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreService.scala

_Remove `verifyValue` from `ValuesResponderV2`_
Tests should assure the create and update logic correctness. If after the update a problem is detected it is too late anyway, the change in the persistence store was already performed.
_Remove `CreateValueRequestV2`_
Expose and use `org.knora.webapi.responders.v2.ValuesResponderV2#createValueV2` directly without the `MessageRelay` indirection.

refactor: Speed up value creation and update DEV-2473

---

integration/src/test/scala/org/knora/webapi/models/filemodels/FileModels.scala
integration/src/test/scala/org/knora/webapi/models/filemodels/FileModelsSpec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ValuesRouteV2.scala

refactor: Remove ValueUpdateRequestV2 and DeleteValueRequestV2 NO-TICKET

---

docs/03-endpoints/api-v2/query-language.md

docs: minor Gravsearch docs fixes

---

docker-compose.yml
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportService.scala

chore(ProjectImportService): improve logging

---

integration/src/test/scala/org/knora/webapi/E2ESpec.scala
integration/src/test/scala/org/knora/webapi/R2RSpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/JSONLDHandlingV2R2RSpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala

There were some bugs in the writing of test data files, because paths weren't up to date (which wasn't tested, of course - only reading is).  
And while I was at it, I did some improvements to all of the test files which rely on generated test data. With these changes, issues like this shouldn't happen so easily anymore.

test: improve file path resolving logic for generated test data files

---

webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala

refactor: remove throws from values responder DEV-2568

---

webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala

Refactor: Remove throws from OntologyResponderV2 DEV-2579 

---

docker-compose.yml

chore: Update app in docker-compose

---

build.sbt

For real this time.
This test passed:
```scala
zio.test.test("") {
val foo = Option("HEAD")
.map(_.trim)
.filter(b => !(b == "main" || b == "HEAD"))
assertTrue(foo.isEmpty)
},
```

chore: Remove -HEAD from published docker tag when building a git tag

---

integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
integration/src/test/scala/org/knora/webapi/util/cache/CacheUtilSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesUtilADM.scala
webapi/src/main/scala/org/knora/webapi/messages/util/rdf/jenaimpl/JenaModel.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/GravsearchParser.scala
webapi/src/main/scala/org/knora/webapi/responders/IriLocker.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala
webapi/src/main/scala/org/knora/webapi/util/ActorUtil.scala
webapi/src/main/scala/org/knora/webapi/util/FileUtil.scala
webapi/src/main/scala/org/knora/webapi/util/cache/CacheUtil.scala

Assign the value to a non-existent variable `val _` where possible. Change the return value of methods in order expose the return value. Remove unused code.

refactor: Remove compiler warning stemming from -Wvalue-discard

---

.github/workflows/check-pr-title

This PR adds the PR title check action, that will prevent merging PRs with bad titles.

chore: add GH action that checks PR title

---

.github/workflows/check-pr-title.yml

chore: Update and rename check-pr-title workflow

---

docker-compose.yml
project/Dependencies.scala

https://github.com/dasch-swiss/docker-apache-jena-fuseki/releases/tag/2.1.1
https://github.com/dasch-swiss/dsp-das/releases/tag/v10.23.5

chore: Update dependencies fuseki and app

---

docker-compose.yml
project/Dependencies.scala

chore: Update Fuseki DEV-2743

---

project/Dependencies.scala
webapi/src/main/scala/dsp/valueobjects/Project.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/MaintenanceRequests.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/MaintenanceService.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala
webapi/src/test/scala/org/knora/webapi/TestDataFactory.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/api/service/MaintenanceServiceLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/common/repo/service/AbstractInMemoryCrudRepository.scala
webapi/src/test/scala/org/knora/webapi/store/triplestore/TestDatasetBuilder.scala

Simply add a service which is able to fix the still image dimensions.
In a followup PR I will expose this service via an endpoint.

feat: Add maintenance action for fixing top-left dimension values DEV-2803

---

docs/03-endpoints/api-admin/projects.md
webapi/src/main/scala/dsp/valueobjects/RestrictedViewSize.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala

feat: add default value of projectRestrictedViewSize (DEV-2626)

---

.github/workflows/check-pr-title.yml

Only allow upper case letters for the first letter of the actual commit.
Since all PR titles are included in the release notes the first letter of the commit message should be upper case. 
This will improve the look of our [release notes which are currently mixed case](https://github.com/dasch-swiss/dsp-api/releases/tag/v30.4.0).

chore: Improve PR title check

---

.github/workflows/build-and-test.yml

chore: Use main branch for GitHub for preparation steps

---

.github/workflows/create-release.yml

Follow the documentation: https://github.com/marketplace/actions/release-please-action

chore: Use correct syntax in release please configuration

---

.github/workflows/create-release.yml

https://github.com/dasch-swiss/dsp-api/actions/runs/6611492148/job/17955472761

chore: Add missing component to release please GitHub action

---

.github/workflows/create-release.yml

chore: Update PR title template

---

integration/src/test/scala/org/knora/webapi/ITTestDataFactory.scala
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectsResponderADMSpec.scala
webapi/src/main/scala/dsp/valueobjects/Project.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsEndpointsRequests.scala
webapi/src/test/scala/dsp/valueobjects/ProjectSpec.scala
webapi/src/test/scala/org/knora/webapi/TestDataFactory.scala

Issue Number: DEV-2892
Main changes are in `Project` and `ProjectSpec` files, other are the name refactoring noise.

fix: Fix project name, description and keywords value objects (DEV-2892)

---

project/Dependencies.scala

Bump sipi version.
Issue Number: DEV-2887

chore: Bump sipi version

---

.github/pull_request_template.md
.github/workflows/check-pr-title.yml

https://www.conventionalcommits.org/en/v1.0.0/#specification

build(PRs): Add 'perf' as allowed prefix for PR titles

---

project/Dependencies.scala

chore: Bump Sipi version to 3.8.3

---

docker-compose.yml

no issue number, just bumping the version of the app

chore(docker-compose): Bump app version to 11.1.0

---

webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala

refactor: Use KnoraRepo instead of MessageRelay in ResourcesResponderV2

---

project/Dependencies.scala

chore: Bump Sipi version to 3.8.5

---

project/Dependencies.scala

chore: Bump Sipi version to 3.8.6

---

project/Dependencies.scala

chore: Bump Sipi version to 3.8.7

---

.github/workflows/build-and-test.yml
.github/workflows/scala-steward.yml
build.sbt

chore: Migrate to Java 21 and remove usage of Java 17 (DEV-3146)

---

webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala

fix: Let DspIngestClientLive get a fresh jwt for each request

---

webapi/src/main/resources/application.conf

fix: Allow all mime types in API that are returned by Ingest (DEV-3163)

---

webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/Codecs.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsEndpointsRequests.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/RestrictedViewSize.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraProjectRepo.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/setProjectRestrictedViewSettings.scala.txt
webapi/src/test/scala/dsp/valueobjects/RestrictedViewSizeSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/repo/KnoraProjectRepoInMemory.scala

refactor: Use RestrictedViewSize in ProjectSetRestrictedViewSizeRequest

---

project/Dependencies.scala

chore: Bump Sipi to 3.8.11

---

integration/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala

fix: Only allow System Administrators to create users

---

.github/workflows/build-and-test.yml

Reduces the duration of our integration test runs from ~23min to ~18min, which is not a huge difference, but still an improvement, I feel.

chore(CI): Run integration tests on actuated again

---

.scala-steward.conf
webapi/src/main/scala/org/knora/webapi/messages/util/DateUtil.scala

I just remind myself that we had `jodd` added to update exceptions. It most probably wouldn't break anything, but I removed it just to be on the safe side.

chore: Remove jodd dependency leftovers

---

integration/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
project/Dependencies.scala

chore: Remove chill, scallop dependency (DEV-3263) (DEV-3262)

---

integration/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
integration/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
webapi/src/main/scala/dsp/valueobjects/LanguageCode.scala
webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/messages/store/cacheservicemessages/CacheServiceMessages.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/Codecs.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/UsersRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/User.scala

refactor: Migrate `GET /admin/users/iri/<userIri>/*memberships` and `POST /admin/users` to tapir

---

docker-compose.yml

chore: Update dsp-app image in docker-compose.yml to v11.4.1

---

docker-compose.yml

chore: Update APP to v11.5.1

---

project/Dependencies.scala

chore: Bump Sipi to 3.8.12

---

docker-compose.yml

chore: Update dsp-app to v11.6.4

---

integration/src/test/scala/org/knora/webapi/responders/admin/UsersResponderSpec.scala
webapi/src/main/scala/dsp/errors/Errors.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponder.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/UsersEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/UsersRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/UserService.scala

- **Move add groups methods from UsersResponder to RestService**
- **Move validation business logic from RestService to UserService**
- **Merge UserResponseADM with UserOperationResponseADM**
- **fmt**

refactor: Move code from UsersResponder to UserService and UserRestService

---

.codecov.yml

chore: Remove Codecov annotations

---

docker-compose.yml

build: Add DSP-INGEST to docker network

---

test_data/upgrade/pr1746.trig

chore: Remove invalid test data

---

integration/src/test/scala/org/knora/sipi/SipiIT.scala
integration/src/test/scala/org/knora/webapi/e2e/admin/AdminFilesE2ESpec.scala
integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/messages/admin/responder/sipimessages/SipiMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/FilesEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala

[DO NOT MERGE] Feat/more spray removal

---

.github/CODEOWNERS

chore: Add CODEOWNERS (DEV-3378)

---

docker-compose.yml

chore: Update dsp-app to v11.7.1

---

integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyFormatsE2ESpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala

test: Move test for serving ontologies in different formats to separate file

---

integration/src/test/scala/org/knora/webapi/responders/v2/SearchResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/OntologyRepo.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/ResourceInfoLayers.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/api/service/RestResourceInfoService.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/domain/ResourceInfoRepo.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/api/service/MaintenanceServiceSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/ontology/repo/service/OntologyRepoLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/resourceinfo/api/LiveRestResourceInfoServiceSpec.scala
webapi/src/test/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala

- **Remove @accessible from TestTripleStore**
- **Remove @accessible from ResourceInfoRepo**
- **Remove @accessible from RestResourceInfoService and inline trait**
- **Remove @accessible from SearchResponderV2**
- **Remove @accessible from OntologyRepo**

refactor: Remove accessible makro (Scala3 perparation)

---

webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsADMRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportService.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectExportServiceStub.scala

feat: Add additional project export route that awaits the process

---

webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala

fix: Error message does not interpolate invalid property IRI

---

docker-compose.yml

chore: Update dsp-app to v11.7.4

---

project/Dependencies.scala

chore: Bump sipi to 3.10.1

---

integration/src/test/scala/org/knora/webapi/E2EZSpec.scala
integration/src/test/scala/org/knora/webapi/e2ez/SampleE2ESpec.scala
webapi/src/main/scala/org/knora/webapi/routing/JwtService.scala

- uses live clock in e2e spacs (so that tokens aren't valid in 1970 but in the present)
- adapts sample test to use a token
- moves sample e2e spec to separate package

test: Improve E2EZSpec

---

webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala

chore: Remove unused constants

---

docker-compose.yml
webapi/src/main/scala/org/knora/webapi/util/Logger.scala

Tested locally with test code, however, docker-compose hasn't been tested, but the definition is correct.

chore: Use env variable for root log level (DEV-3410)

---

webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/AdministrativePermissionRepo.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/RdfConversions.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/Vocabulary.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/AbstractEntityRepo.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/AdministrativePermissionRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraUserRepoLive.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/errors/Errors.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR3110.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR3111.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR3112.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/model/AdministrativePermissionRepoSpec.scala
webapi/src/test/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala

refactor: Introduce AdministrativePermissionRepo and AbstractEntityRepo

---

project/Dependencies.scala
webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JenaModel.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponder.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraUserRepoLive.scala
webapi/src/test/scala/org/knora/webapi/store/triplestore/api/TriplestoreServiceInMemory.scala

Overall, just two deprecations. I added cheap "sort" hacks to when the order of links in some vector wasn't the same, which shouldn't affect behavior.
Issue Number: DEV-3426

chore: Bump jena to 5.0.0 (DEV-3426)

---

project/Dependencies.scala

chore: Bump Sipi to v3.12.2

---

project/plugins.sbt

chore: Update sbt-buildinfo to v0.12.0

---

docker-compose.yml

chore: Update dsp-app to v11.8.0

---

integration/src/test/scala/org/knora/webapi/core/LayersTest.scala
integration/src/test/scala/org/knora/webapi/responders/v2/SearchResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportServiceIT.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/core/MessageRelay.scala
webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilADM.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectImportService.scala
webapi/src/main/scala/org/knora/webapi/slice/common/api/AuthorizationRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/resourceinfo/domain/IriConverter.scala
webapi/src/test/scala/dsp/valueobjects/SchemaCommandsSpec.scala
webapi/src/test/scala/org/knora/webapi/core/MessageRelaySpec.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/api/service/AuthorizationRestServiceSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/ontology/repo/OntologyCacheFakeSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/resourceinfo/api/IriConverterLiveSpec.scala

- **chore: Remove @accessible from MessageRelay**
- **chore: Remove @accessible from AuthorizationRestService and inline trait**
- **chore: Remove @accessible from ProjectImportService and inline trait**
- **chore: Remove @accessible from IriConverter and inline trait**

chore: Remove @accessible macro from some places (Scala 3 preparation)

---

webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraGroupService.scala

chore: Remove unused dependency from KnoraGroupService

---

.github/workflows/build-and-test.yml
docs/01-introduction/file-formats.md
docs/03-endpoints/api-v2/editing-values.md
docs/03-endpoints/api-v2/text/tei-xml.md
docs/05-internals/design/api-admin/administration.md
docs/05-internals/design/api-v2/overview.md
docs/05-internals/design/principles/consistency-checking.md
justfile

Markdownlint checks if the documentation files comply with the Markdown syntax. This is important for a correct building of the docs with `mkdocs` and correct display on https://docs.dasch.swiss/.

docs: Add markdownlint check to CI

---

docs/02-dsp-ontologies/knora-base.md

docs: Add documentation for additional properties on Segment

---

docker-compose.yml

chore: Update dsp-app to v11.9.0

---

docker-compose.yml

chore: Remove deprecated version in docker compose file

---

project/Dependencies.scala

chore: Update Apache-Jena-Fuseki container to v5.0.0-2

---

webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala

[Add plugin for v37](https://github.com/dasch-swiss/dsp-api/blob/main/webapi/src/main/resources/knora-ontologies/knora-base.ttl#L23)

fix: Add missing upgrade plugin after knora-base update (DEV-3473)

---

docker-compose.yml

chore: Update dsp-app to v11.9.1

---

docker-compose.yml

chore: Fix apache-jena-fuseki update

---

docs/02-dsp-ontologies/knora-base.md

docs: Improve documentation on segments

---

webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponder.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/ListsEndpointsHandlers.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ListRestService.scala

refactor: Split list handlers and rest service

---

integration/src/test/scala/org/knora/webapi/testservices/TestClientService.scala

refactor: TestClientService: STTP instead of Apache HTTP (DEV-1627)

---

webapi/src/main/scala/org/knora/webapi/store/iiif/impl/SipiServiceLive.scala

refactor: SipiServiceLive: Sttp instead of Apache HTTP (DEV-1627)

---

integration/src/test/scala/org/knora/webapi/E2ESpec.scala
integration/src/test/scala/org/knora/webapi/ITKnoraLiveSpec.scala
integration/src/test/scala/org/knora/webapi/it/v2/StandoffRouteV2ITSpec.scala
integration/src/test/scala/org/knora/webapi/testservices/TestClientService.scala
webapi/src/main/scala/org/knora/webapi/messages/store/sipimessages/SipiMessages.scala
webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/FusekiAPI.scala
webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
webapi/src/main/scala/org/knora/webapi/messages/util/rdf/SparqlSelectResult.scala
webapi/src/main/scala/org/knora/webapi/slice/infrastructure/JwtService.scala
webapi/src/main/scala/org/knora/webapi/store/iiif/impl/SipiServiceLive.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClientLiveSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/infrastructure/JwtServiceLiveSpec.scala

refactor: Remove Spray Json from files refactored during DEV-1627

---

docker-compose.yml

chore: Remove LOCAL_HOME from docker compose

---

webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala

chore: Add ontology constants for text value types

---

test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
webapi/src/main/resources/knora-ontologies/knora-base.ttl
webapi/src/main/scala/org/knora/webapi/package.scala

chore: Add missing labels and comment to relatesToValue

---

docker-compose.yml
project/Dependencies.scala

chore: Update apache-jena-fuseki to 5.0.0-3

---

docker-compose.yml

chore: Update dsp-app to v11.11.0

---

webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala

fix: Do not ignore the cardinality check result when updating the cardinalties (DEV-3841)

---

docs/02-dsp-ontologies/introduction.md

Delete an unnecessary link that points to the same paragraph.
Issue Number: DEV-3810

docs: Update documentation

---

webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala

fix: Add missing /v2/[lists|node]/:listIri to ApiRoutes

---

webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyCache.scala

Rather than throwing an exception simply skip unknown ontologies/classes when determining cardinalities during a class update.

fix: Do not fail when updating class with external ontologies (DEV-3879)

---

project/Dependencies.scala

New Sipi release includes ijg JPEG decoder lib's update.
Issue Number: DEV-3474

chore: Update Sipi (DEV-3474)

---

webapi/src/main/scala/org/knora/webapi/slice/resources/repo/service/ResourcesRepoLive.scala

fix: Decimals without decimal point lead to inconsistent data (DEV-3927)

---

project/Dependencies.scala

chore: Bump Sipi to v3.13.0

---

integration/src/test/resources/application.conf
integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala

1. Found bug, it looks like it could be old escaping code. The fix has been tested with really nasty output / fuzz testing in OntologyV2R2RSpec. If someone could vouch for the correctness, I'd be grateful.
2. First commit silences the wall of text about slow local queries only for tests.

fix: Fix escaping issues in labels, add fuzz testing to make sure (DEV-3976)

---

docs/03-endpoints/api-admin/projects.md
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectRestServiceSpec.scala
webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponder.scala

chore: Change default DOAPs according to the defined requirements (DEV-4042)

---

docker-compose.yml
project/Dependencies.scala

chore: Update apache-jena-fuseki to 5.1.0

---

.github/workflows/create-release.yml

Because I have improved a little bit the prefixes in dsp-meta, did something similar here.

chore: Improve Release Please prefixes and CHANGELOG sections

---

integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala

refactor: Replace `appActor ! CreateResourceRequestV2` with method call on responder

---

integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala

- **refactor: Remove code warnings in IntelliJ**
- **test: Add test for providing an empty list as values for a required property**

test: Add test for providing an empty list as values for a required property (DEV-4017)

---

integration/src/test/scala/org/knora/sipi/SipiIT.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/DspIngestClient.scala

refactor: Replace deprecated Client.request with equivalent Client.batched

---

webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
webapi/src/main/scala/org/knora/webapi/util/ZioHelper.scala
webapi/src/test/scala/org/knora/webapi/util/ZioHelperSpec.scala

IMHO this is making the code better to understand:
- **refactor: Replace ZioHelper.sequence with ZIO.foreach**
- **refactor: Remove unused code**

refactor: Replace ZioHelper.sequence with ZIO.foreach

---

docs/01-introduction/file-formats.md
docs/03-endpoints/api-v2/editing-values.md
sipi/scripts/file_info.lua
webapi/src/main/resources/application.conf

This should be enough, it seems like not all extensions are tested in unit tests, so this was tested only locally.

feat: Allow uploading JSON text files (DEV-4222)

---

webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala

fix: Take language into account when checking for duplicate TextValues (DEV-4264)

---

integration/src/test/scala/org/knora/webapi/testservices/TestClientService.scala

test: Use Authorization header instead of url parms in TestClientService

---

integration/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/slice/common/JenaModelOps.scala
webapi/src/main/scala/org/knora/webapi/slice/common/ModelOps.scala
webapi/src/test/scala/org/knora/webapi/messages/v2/responder/valuemessages/CreateValueV2Spec.scala
webapi/src/test/scala/org/knora/webapi/slice/common/JenaModelOpsSpec.scala
webapi/src/test/scala/org/knora/webapi/slice/common/JsonLdTestUtil.scala
webapi/src/test/scala/org/knora/webapi/slice/common/KnoraApiValueModelSpec.scala

- **Introduce KnoraApiValueModel**
- **Add tests transformators for JSON-LD permutations**
- **Ensure constraints when creating the KnoraApiValueModel**
- **Integrate the `KnoraApiValueModel` into parts of the `CreateValueV2.fromJsonLD` function**

refactor: Start replacing Json-LD parsing with using an RDF model

---

.github/workflows/publish-docs.yml

docs: Publish API docs to github pages

---

integration/src/test/scala/org/knora/webapi/messages/util/search/SparqlTransformerSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/transformers/OntologyInferencer.scala

fix: Attempt to optimize OntologyInferencer (DEV-4063)

---

test_data/generated_test_data/ontologyR2RV2/anythingOntologySimple.jsonld
test_data/generated_test_data/ontologyR2RV2/anythingOntologyWithValueObjects.jsonld
test_data/generated_test_data/ontologyR2RV2/anythingOntologyWithValueObjects.ttl
test_data/project_data/anything-data.ttl
test_data/project_ontologies/anything-onto.ttl

test: Add test data to anything project

---

docs/02-dsp-ontologies/knora-base.md

docs: Remove outdated statement on TEI in Standoff support

---

docker-compose.yml

chore: Update dsp-app to v11.22.5

---

test_data/generated_test_data/ontologyR2RV2/knoraApiDateValue.jsonld
test_data/generated_test_data/ontologyR2RV2/knoraApiOntologySimple.jsonld
test_data/generated_test_data/ontologyR2RV2/knoraApiOntologyWithValueObjects.jsonld
webapi/src/main/resources/knora-ontologies/knora-base.ttl
webapi/src/main/scala/org/knora/webapi/package.scala

fix: Add rdfs:label to knora-base resources to ensure this is present for  isSegmentOfValue properties (DEV-4505)

---

integration/src/test/scala/org/knora/webapi/testcontainers/DspIngestTestContainer.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/AbstractEntityRepo.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/AdministrativePermissionRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/DefaultObjectAccessPermissionRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraGroupRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraProjectRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/repo/service/KnoraUserRepoLive.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/repo/service/DefaultObjectAccessPermissionRepoLiveSpec.scala

This bug only [surfaces when updating some dependencies](https://github.com/dasch-swiss/dsp-api/runs/35701975854#r53).
Hence this needs to be merged before https://github.com/dasch-swiss/dsp-api/pull/3456

fix: Find the right doap when looking for by ForWhat

---

integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
integration/src/test/scala/org/knora/webapi/messages/admin/responder/IntegrationTestAdminJsonProtocol.scala
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectRestServiceSpec.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/ProjectInfo.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/Examples.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectServiceSpec.scala

refactor: Make Project.shortname typed

---

integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
integration/src/test/scala/org/knora/webapi/messages/admin/responder/IntegrationTestAdminJsonProtocol.scala
integration/src/test/scala/org/knora/webapi/models/filemodels/FileModels.scala
integration/src/test/scala/org/knora/webapi/models/filemodels/FileModelsSpec.scala
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectRestServiceSpec.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/ProjectInfo.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/Examples.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala
webapi/src/main/scala/org/knora/webapi/slice/common/ApiComplexV2JsonLdRequestParser.scala
webapi/src/main/scala/org/knora/webapi/slice/common/ValueTypes.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectServiceSpec.scala

refactor: Make Project.shortcode typed

---

integration/src/test/scala/org/knora/webapi/ProjectEraseIT.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/ontology/CardinalitiesV2E2ESpec.scala
integration/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADMSpec.scala
integration/src/test/scala/org/knora/webapi/responders/admin/GroupRestServiceSpec.scala
integration/src/test/scala/org/knora/webapi/responders/admin/PermissionsResponderSpec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/UserProfile.scala
integration/src/test/scala/org/knora/webapi/slice/admin/domain/service/KnoraUserToUserConverterSpec.scala
webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyTriplestoreHelpers.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsEndpointsRequestsAndResponses.scala
webapi/src/main/scala/org/knora/webapi/slice/common/ValueTypes.scala
webapi/src/main/scala/org/knora/webapi/slice/common/jena/ResourceOps.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologyV2RequestParser.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/createOntology.scala.txt
webapi/src/test/scala/org/knora/webapi/slice/ontology/api/OntologyV2RequestParserSpec.scala

feat: Support jsonld for create ontology requests (DEV-4344)

---

integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
integration/src/test/scala/org/knora/webapi/messages/admin/responder/IntegrationTestAdminJsonProtocol.scala
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectRestServiceSpec.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/ProjectInfo.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/Examples.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala

refactor: Make Project.longname typed

---

.markdownlint.yml
docs/03-endpoints/api-admin/lists.md
docs/03-endpoints/api-admin/permissions.md
docs/03-endpoints/api-v2/authentication.md
docs/03-endpoints/api-v2/editing-values.md
docs/03-endpoints/api-v2/ontology-information.md
docs/05-internals/design/principles/store-module.md
docs/05-internals/design/principles/triplestore-updates.md
docs/06-sipi/sipi-and-dsp-api.md
docs/10-migration-guides/index.md

deprecated: Move deprecation warnings to deprecation section in docs

---

project/Dependencies.scala

Integrate https://github.com/dasch-swiss/sipi/pull/463

chore: Update SIPI to 3.15.0

---

integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
integration/src/test/scala/org/knora/webapi/messages/admin/responder/IntegrationTestAdminJsonProtocol.scala
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectRestServiceSpec.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/ProjectInfo.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala

refactor: Make Project.logo typed

---

webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyHelpers.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyTriplestoreHelpers.scala
webapi/src/main/scala/org/knora/webapi/slice/common/KnoraIris.scala

refactor: Move creating OntologyIri code to OntologyIri

---

docs/03-endpoints/api-v2/text/standard-standoff.md
integration/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala

docs: Update documentation on footnotes in richtext (DEV-4567)

---

integration/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
integration/src/test/scala/org/knora/webapi/messages/admin/responder/IntegrationTestAdminJsonProtocol.scala
integration/src/test/scala/org/knora/webapi/responders/admin/ProjectRestServiceSpec.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/ProjectInfo.scala
integration/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/Examples.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/ProjectsMessagesADM.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectService.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/ProjectServiceSpec.scala

Make `Project.status` typed `KnoraProject.Status`.

refactor: Make Project.status typed

---

webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala

- **chore: Add request uri to failure message**

chore: Add context to error failed to connect to Fuseki

---

integration/src/test/scala/org/knora/webapi/R2RSpec.scala
integration/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
webapi/src/main/scala/dsp/errors/Errors.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/ApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/common/KnoraIris.scala
webapi/src/main/scala/org/knora/webapi/slice/common/api/ApiV2Endpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/common/api/DocsGenerator.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologiesEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologiesEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologyApiModule.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologyApiRoutes.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/service/OntologiesRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/domain/service/IriConverter.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/repo/service/OntologyRepoLive.scala

refactor: Migrate some v2/ontologies routes to Tapir endpoints (DEV-4657)

---

webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEndpoints.scala

feat: Rename LicenseDto label-en to labelEn

---

integration/src/test/scala/org/knora/webapi/it/v2/LegalInfoE2ESpec.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/Pagination.scala

feat: Use camel case in Pagination responses for json keys

---

project/Dependencies.scala

https://github.com/dasch-swiss/sipi/releases/tag/v3.15.1

chore: Update Sipi to 3.15.1

---

integration/src/test/scala/org/knora/webapi/e2ez/SearchE2EZSpec.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
webapi/src/main/scala/org/knora/webapi/slice/search/api/SearchEndpoints.scala

feat: Add new route for incoming links (DEV-4722)

---

docker-compose.yml

chore: Update DSP-APP to v11.27.0

---

Makefile
webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/InferenceOptimizationService.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2Module.scala
webapi/src/main/scala/org/knora/webapi/slice/search/api/SearchEndpoints.scala

feat: Limit Gravsearch to a single project by query parameter

---

webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologiesEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologiesEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/service/OntologiesRestService.scala

* `PUT  v2/ontologies/classes`
* `POST v2/ontologies/classes`
* `DELETE v2/ontologies/classes/comment`

feat: Migrate some ontologies routes to Tapir, adds OpenAPI docs(DEV-4657)

---

webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
webapi/src/main/scala/org/knora/webapi/routing/RouteUtilZ.scala
webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologiesEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologiesEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologyApiModule.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/service/OntologiesRestService.scala

- **feat: Migrate GET  v2/ontologies/allentities to Tapir**
- **feat: Migrate GET v2/ontologies/metadata to Tapir**
- **feat: Migrate GET v2/ontologies/metadata/:paths to Tapir**
- **feat: Migrate PUT v2/ontologies/metadata to Tapir**

feat: Migrate more ontology api endpoinst to Tapir (DEV-4657)

---

docker-compose.yml

chore: Align dsp-app app version with prod

---

docs/01-introduction/legal-info.md

Fixes some broken links in the documentation

docs: Fix broken links in documentation

---

integration/src/test/scala/org/knora/webapi/ProjectEraseIT.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/KnoraUserService.scala

The method which does not enforce the constrain was only used in tests. No impact on production code yet.

fix: Align constraints for adding user to admin group for all service methods

---

integration/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/resources/CreateResourceV2Handler.scala

feat: Allow duplicate Values (DEV-4861)

---

docs/01-introduction/legal-info.md

docs: Update documentations on licenses (DEV-4851) 

---

webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/model/Pagination.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/model/LegalInfoModel.scala

In https://github.com/softwaremill/tapir/issues/3922#issuecomment-2866832846 the solution is outlined.

refactor: Combine PagedResponse schemas into a single given

---

integration/src/test/scala/org/knora/webapi/e2e/v2/ontology/InputOntologyV2.scala
integration/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ontology/OntologyHelpers.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/api/OntologyV2RequestParser.scala
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/changeOntologyMetadata.scala.txt
webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/createOntology.scala.txt
webapi/src/test/scala/org/knora/webapi/slice/ontology/api/OntologyV2RequestParserSpec.scala

fix: Do not allow empty comment when updating an ontology (DEV-4881)

---

integration/src/test/scala/org/knora/webapi/E2EZSpec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ValuesEraseSpec.scala
integration/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala
webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
webapi/src/main/scala/org/knora/webapi/messages/util/rdf/SparqlSelectResult.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
webapi/src/main/scala/org/knora/webapi/responders/IriLocker.scala
webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
webapi/src/main/scala/org/knora/webapi/slice/common/ApiComplexV2JsonLdRequestParser.scala
webapi/src/main/scala/org/knora/webapi/slice/common/KnoraIris.scala
webapi/src/main/scala/org/knora/webapi/slice/common/jena/ResourceOps.scala
webapi/src/main/scala/org/knora/webapi/slice/common/repo/rdf/RdfModel.scala
webapi/src/main/scala/org/knora/webapi/slice/common/repo/rdf/Vocabulary.scala
webapi/src/main/scala/org/knora/webapi/slice/ontology/CoreModule.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/api/ResourcesApiModule.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/api/ValuesEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/api/ValuesEndpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/api/service/ValuesRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/repo/service/ResourcesRepoLive.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/repo/service/ValueRepo.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/impl/TriplestoreServiceLive.scala
webapi/src/test/scala/org/knora/webapi/slice/common/jena/ResourceOpsSpec.scala

On top of @seakayone's PR with two commits.
This PR defines the routes `/v2/values/erase` and `/v2/values/erasehistory`.

feat: Value Erasing, except standoff with links (DEV-4701)

---

webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEntpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsLegalInfoRestService.scala

feat: Allow public read access to project licenses (DEV-4913)

---

integration/src/test/scala/org/knora/webapi/e2e/admin/AdminProjectsEndpointE2ESpec.scala

test: Add e2e assertion for providing custom enabled licenses during project creation (DEV-4930)

---

webapi/src/main/scala/org/knora/webapi/slice/resources/api/MetadataEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/service/MetadataService.scala

Add column and reorder fields.

feat: Add ark url with timestamp to resource metadata export (DEV-4950)

---

docker-compose.yml
webapi/src/main/resources/knora-ontologies/knora-base.ttl
webapi/src/main/scala/org/knora/webapi/package.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdatePlan.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR3612.scala
webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPRXXXX.scala

feat: Add default CopyrightHolder and Licenses to projects without (DEV-4957)

---

integration/src/test/scala/org/knora/webapi/responders/v2/ValuesEraseSpec.scala
project/Dependencies.scala

* 📦 [dev.zio:zio](https://github.com/zio/zio) from `2.1.17` to `2.1.19`
+ 📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.19) - [Version Diff](https://github.com/zio/zio/compare/v2.1.17...v2.1.19)
* 📦 [dev.zio:zio-macros](https://github.com/zio/zio) from `2.1.17` to `2.1.19`
+ 📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.19) - [Version Diff](https://github.com/zio/zio/compare/v2.1.17...v2.1.19)
* 📦 [dev.zio:zio-test](https://github.com/zio/zio) from `2.1.17` to `2.1.19`
+ 📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.19) - [Version Diff](https://github.com/zio/zio/compare/v2.1.17...v2.1.19)
* 📦 [dev.zio:zio-test-sbt](https://github.com/zio/zio) from `2.1.17` to `2.1.19`
+ 📜 [GitHub Release …

chore: Update zio from 2.1.17 to 2.1.19

---

webapi/src/main/resources/application.conf

With this feature enabled it is not possible anymore to create FileValues without any legal infos.

feat: Enable full license check on creating a FileValue (DEV-4956)

---

integration/src/test/resources/application.conf
webapi/src/main/resources/application.conf
webapi/src/main/scala/org/knora/webapi/config/AppConfig.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/AdminDomainModule.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/LegalInfoService.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/LegalInfoServiceSpec.scala

refactor: Remove feature switch ENABLE_FULL_LICENSE_CHECK

---

webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/ProjectsLegalInfoEntpointsHandler.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/api/service/ProjectsLegalInfoRestService.scala
webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/LegalInfoService.scala
webapi/src/test/scala/org/knora/webapi/slice/admin/domain/service/LegalInfoServiceSpec.scala

* Add public endpoint `GET /admin/projects/shortcode/:shortcode/licenses/:licenseIri endpoint`

feat: Add get project license by iri endpoint

---

docs/01-introduction/file-formats.md

Support has been implemented in https://github.com/dasch-swiss/dsp-ingest/pull/364/files
This PR updates the api documentation

feat: Add HTML and epub to the documented list of supported file formats (DEV-5080)

---

webapi/src/main/resources/application.conf
webapi/src/main/scala/org/knora/webapi/slice/common/ApiComplexV2JsonLdRequestParser.scala

- **feat: Add supported mime-type for epub and html**
- **import fail message**

feat: Add new mimetypes to configuration (DEV-5085)

---

webapi/src/main/scala/dsp/valueobjects/Iri.scala
webapi/src/main/scala/org/knora/webapi/messages/util/standoff/StandoffTagUtilV2.scala

fix: Value creation fails if a link tag in standoff does not have a protocol (DEV-5142)

---

project/Dependencies.scala

chore: Update sipi to 3.16.2

---

docker-compose.yml

chore: Use latest tag for app in local development

---

.editorconfig
AGENTS.md
README.md

docs: Add AGENTS.md

---

webapi/src/main/scala/org/knora/webapi/messages/util/standoff/StandoffTagUtilV2.scala

Refactored the `StandoffTagUtilV2` class by extracting the tag creation logic into a separate method `createStandoffTag`. This improves code organization by moving the large tag creation logic from the main method into a dedicated helper function with proper parameter passing.
The change maintains all existing functionality while making the code more maintainable and easier to understand by reducing nesting levels in the main method.

refactor: Extract method for readability

---

.github/workflows/build-and-test.yml

build(CI): Simplify build-and-test github action

---

.github/workflows/build-and-test.yml

build(CI): Remove the 'on push' trigger

---

modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/ontology/CardinalitiesV2E2ESpec.scala

refactor: Migrate CardinalitiesV2E2ESpec to zio-test

---

modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/OntologyFormatsE2ESpec.scala
modules/testkit/src/main/scala/org/knora/webapi/testservices/TestApiClient.scala

refactor: Migrate OntologyFormatsE2ESpec to zio-test

---

modules/test-e2e/src/test/scala/org/knora/webapi/it/v2/KnoraSipiIntegrationV2ITSpec.scala
modules/testkit/src/main/scala/org/knora/webapi/testservices/TestSipiApiClient.scala

- **refactor: Replace pekko http client with TestApiClient in KnoraSipiIntegrationV2ITSpec**

refactor: Migrate KnoraSipiIntegrationV2ITSpec to zio test

---

modules/test-it/src/test/scala/org/knora/webapi/responders/v2/SearchResponderV2Spec.scala

* Migrate SearchResponderV2Spec from pekko/scalaTest to zio

refactor: Migrate SearchResponderV2Spec from pekko/scalaTest to zio (DEV 5311)

---

modules/test-e2e/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/api/ResourcesEndpoints.scala
webapi/src/main/scala/org/knora/webapi/slice/resources/api/ResourcesEndpointsHandler.scala

Commits weren't pushed from the local branch. Please forgive me.

feat: Convert /v2/resources/candelete to GET
